// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AICHAT_H
#define UI_AICHAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIChat
extern void ui_AIChat_screen_init(void);
extern void ui_AIChat_screen_destroy(void);
extern lv_obj_t * ui_AIChat;
extern lv_obj_t * ui_AIChatTitleCont;
extern lv_obj_t * ui_AIChatReturnImg;
extern lv_obj_t * ui_AIChatTitleLab;
extern void ui_event_AIChatReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_AIChatReturnBtn;
extern void ui_event_AIChatVolumBtn2(lv_event_t * e);
extern lv_obj_t * ui_AIChatVolumBtn2;
extern lv_obj_t * ui_AIChatVolumImg3;
extern lv_obj_t * ui_AIChatVolumImg2;
extern lv_obj_t * ui_AIChatVolumImg1;
extern lv_obj_t * ui_AIChatVolumImg0;
extern lv_obj_t * ui_AIChatLabCont;
extern lv_obj_t * ui_AIExpressionImg;
extern lv_obj_t * ui_AngerImg;
extern lv_obj_t * ui_BlinkingImg;
extern lv_obj_t * ui_ConfidenceImg;
extern lv_obj_t * ui_ConfusionImg;
extern lv_obj_t * ui_CoolnessImg;
extern lv_obj_t * ui_CryingImg;
extern lv_obj_t * ui_DeliciousnessImg;
extern lv_obj_t * ui_DescriptionImg;
extern lv_obj_t * ui_DrowsinessImg;
extern lv_obj_t * ui_EmbarrassmeImg;
extern lv_obj_t * ui_FunnyImg;
extern lv_obj_t * ui_HappinessImg;
extern lv_obj_t * ui_InterestImg;
extern lv_obj_t * ui_KissImg;
extern lv_obj_t * ui_LaughHeartilyImg;
extern lv_obj_t * ui_ListeningImg;
extern lv_obj_t * ui_LoveImg;
extern lv_obj_t * ui_NeutralityImg;
extern lv_obj_t * ui_RelaxImg;
extern lv_obj_t * ui_SadnessImg;
extern lv_obj_t * ui_ShockImg;
extern lv_obj_t * ui_SleepyImg;
extern lv_obj_t * ui_SpeechImg;
extern lv_obj_t * ui_StupidityImg;
extern lv_obj_t * ui_ThinkingImg;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_AIChatLabCont2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

