// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AIRECOGNITIONSCR_H
#define UI_AIRECOGNITIONSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIRecognitionScr
extern void ui_AIRecognitionScr_screen_init(void);
extern void ui_AIRecognitionScr_screen_destroy(void);
extern void ui_event_AIRecognitionScr(lv_event_t * e);
extern lv_obj_t * ui_AIRecognitionScr;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_AIRecognitionPageIndexDot1;
extern lv_obj_t * ui_AIRecognitionPageIndexDot2;
extern lv_obj_t * ui_AIRecognitionPageIndexDot0;
extern lv_obj_t * ui_AIRecognitionCont;
extern lv_obj_t * ui_AIRecohnitionWiFiCont;
extern lv_obj_t * ui_AIRecognitionRssi5;
extern lv_obj_t * ui_AIRecognitionRssi4;
extern lv_obj_t * ui_AIRecognitionRssi3;
extern lv_obj_t * ui_AIRecognitionRssi2;
extern lv_obj_t * ui_AIRecognitionRssi1;
extern lv_obj_t * ui_AIRecognitionRssi0;
extern lv_obj_t * ui_AIRecognitionLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

