#include "libraries/lvgl/src/core/lv_obj.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIChat = NULL;
lv_obj_t * ui_AIChatTitleCont = NULL;
lv_obj_t * ui_AIChatReturnImg = NULL;
lv_obj_t * ui_AIChatTitleLab = NULL;
lv_obj_t * ui_AIChatReturnBtn = NULL;
lv_obj_t * ui_AIChatVolumBtn2 = NULL;
lv_obj_t * ui_AIChatVolumImg3 = NULL;
lv_obj_t * ui_AIChatVolumImg2 = NULL;
lv_obj_t * ui_AIChatVolumImg1 = NULL;
lv_obj_t * ui_AIChatVolumImg0 = NULL;
lv_obj_t * ui_AIChatLabCont = NULL;
lv_obj_t * ui_AIExpressionImg = NULL;
lv_obj_t * ui_AngerImg = NULL;
lv_obj_t * ui_BlinkingImg = NULL;
lv_obj_t * ui_ConfidenceImg = NULL;
lv_obj_t * ui_ConfusionImg = NULL;
lv_obj_t * ui_CoolnessImg = NULL;
lv_obj_t * ui_CryingImg = NULL;
lv_obj_t * ui_DeliciousnessImg = NULL;
lv_obj_t * ui_DescriptionImg = NULL;
lv_obj_t * ui_DrowsinessImg = NULL;
lv_obj_t * ui_EmbarrassmeImg = NULL;
lv_obj_t * ui_FunnyImg = NULL;
lv_obj_t * ui_HappinessImg = NULL;
lv_obj_t * ui_InterestImg = NULL;
lv_obj_t * ui_KissImg = NULL;
lv_obj_t * ui_LaughHeartilyImg = NULL;
lv_obj_t * ui_ListeningImg = NULL;
lv_obj_t * ui_LoveImg = NULL;
lv_obj_t * ui_NeutralityImg = NULL;
lv_obj_t * ui_RelaxImg = NULL;
lv_obj_t * ui_SadnessImg = NULL;
lv_obj_t * ui_ShockImg = NULL;
lv_obj_t * ui_SleepyImg = NULL;
lv_obj_t * ui_SpeechImg = NULL;
lv_obj_t * ui_StupidityImg = NULL;
lv_obj_t * ui_ThinkingImg = NULL;
lv_obj_t * ui_AIChatLabCont2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image6 = NULL;
// event funtions
void ui_event_AIChatReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_label_set_text(ui_Label2, "Closing...");
        //_ui_screen_change(&ui_AIChatMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 800, &ui_AIChatMenu_screen_init);
        aichat_exit = true;
    }
}

void ui_event_AIChatVolumBtn2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_VolumSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_VolumSrc_screen_init);
    }
}


void ui_event_Img6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Touch = 1;
    }
}
// build funtions

void ui_AIChat_screen_init(void)
{
    ui_AIChat = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIChat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatTitleCont = lv_obj_create(ui_AIChat);
    lv_obj_remove_style_all(ui_AIChatTitleCont);
    lv_obj_set_width(ui_AIChatTitleCont, 240);
    lv_obj_set_height(ui_AIChatTitleCont, 50);
    lv_obj_set_x(ui_AIChatTitleCont, 0);
    lv_obj_set_y(ui_AIChatTitleCont, -117);
    lv_obj_set_align(ui_AIChatTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatReturnImg = lv_img_create(ui_AIChatTitleCont);
    lv_img_set_src(ui_AIChatReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_AIChatReturnImg, 20);
    lv_obj_set_height(ui_AIChatReturnImg, 20);
    lv_obj_set_x(ui_AIChatReturnImg, -85);
    lv_obj_set_y(ui_AIChatReturnImg, 0);
    lv_obj_set_align(ui_AIChatReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatTitleLab = lv_label_create(ui_AIChatTitleCont);
    lv_obj_set_width(ui_AIChatTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIChatTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AIChatTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatTitleLab, "AI Dialogue");
    lv_obj_set_style_text_color(ui_AIChatTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChatTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatReturnBtn = lv_btn_create(ui_AIChatTitleCont);
    lv_obj_set_width(ui_AIChatReturnBtn, 100);
    lv_obj_set_height(ui_AIChatReturnBtn, 50);
    lv_obj_set_x(ui_AIChatReturnBtn, -70);
    lv_obj_set_y(ui_AIChatReturnBtn, 0);
    lv_obj_set_align(ui_AIChatReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatVolumBtn2 = lv_btn_create(ui_AIChatTitleCont);
    lv_obj_set_width(ui_AIChatVolumBtn2, 100);
    lv_obj_set_height(ui_AIChatVolumBtn2, 50);
    lv_obj_set_x(ui_AIChatVolumBtn2, 70);
    lv_obj_set_y(ui_AIChatVolumBtn2, 0);
    lv_obj_set_align(ui_AIChatVolumBtn2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatVolumBtn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatVolumBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatVolumBtn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatVolumBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatVolumImg3 = lv_img_create(ui_AIChatTitleCont);
    lv_img_set_src(ui_AIChatVolumImg3, &ui_img_icon_voice_01_png);
    lv_obj_set_width(ui_AIChatVolumImg3, 20);
    lv_obj_set_height(ui_AIChatVolumImg3, 20);
    lv_obj_set_x(ui_AIChatVolumImg3, 85);
    lv_obj_set_y(ui_AIChatVolumImg3, 0);
    lv_obj_set_align(ui_AIChatVolumImg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatVolumImg3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatVolumImg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatVolumImg2 = lv_img_create(ui_AIChatTitleCont);
    lv_img_set_src(ui_AIChatVolumImg2, &ui_img_icon_voice_02_png);
    lv_obj_set_width(ui_AIChatVolumImg2, 20);
    lv_obj_set_height(ui_AIChatVolumImg2, 20);
    lv_obj_set_x(ui_AIChatVolumImg2, 85);
    lv_obj_set_y(ui_AIChatVolumImg2, 0);
    lv_obj_set_align(ui_AIChatVolumImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatVolumImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatVolumImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatVolumImg1 = lv_img_create(ui_AIChatTitleCont);
    lv_img_set_src(ui_AIChatVolumImg1, &ui_img_icon_voice_03_png);
    lv_obj_set_width(ui_AIChatVolumImg1, 20);
    lv_obj_set_height(ui_AIChatVolumImg1, 20);
    lv_obj_set_x(ui_AIChatVolumImg1, 85);
    lv_obj_set_y(ui_AIChatVolumImg1, 0);
    lv_obj_set_align(ui_AIChatVolumImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatVolumImg1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatVolumImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatVolumImg0 = lv_img_create(ui_AIChatTitleCont);
    lv_img_set_src(ui_AIChatVolumImg0, &ui_img_icon_voice_04_png);
    lv_obj_set_width(ui_AIChatVolumImg0, 20);
    lv_obj_set_height(ui_AIChatVolumImg0, 20);
    lv_obj_set_x(ui_AIChatVolumImg0, 85);
    lv_obj_set_y(ui_AIChatVolumImg0, 0);
    lv_obj_set_align(ui_AIChatVolumImg0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatVolumImg0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatVolumImg0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatLabCont = lv_obj_create(ui_AIChat);
    lv_obj_remove_style_all(ui_AIChatLabCont);
    lv_obj_set_width(ui_AIChatLabCont, 230);
    lv_obj_set_height(ui_AIChatLabCont, 235);
    lv_obj_set_x(ui_AIChatLabCont, 0);
    lv_obj_set_y(ui_AIChatLabCont, 25);
    lv_obj_set_align(ui_AIChatLabCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatLabCont, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIExpressionImg = lv_obj_create(ui_AIChatLabCont);
    lv_obj_remove_style_all(ui_AIExpressionImg);
    lv_obj_set_width(ui_AIExpressionImg, 70);
    lv_obj_set_height(ui_AIExpressionImg, 70);
    lv_obj_set_x(ui_AIExpressionImg, 0);
    lv_obj_set_y(ui_AIExpressionImg, 80);
    lv_obj_set_align(ui_AIExpressionImg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIExpressionImg, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AngerImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_AngerImg, &ui_img_anger_png);
    lv_obj_set_width(ui_AngerImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AngerImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AngerImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AngerImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AngerImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BlinkingImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_BlinkingImg, &ui_img_blinking_png);
    lv_obj_set_width(ui_BlinkingImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BlinkingImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BlinkingImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BlinkingImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BlinkingImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfidenceImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_ConfidenceImg, &ui_img_confidence_png);
    lv_obj_set_width(ui_ConfidenceImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfidenceImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfidenceImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfidenceImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ConfidenceImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfusionImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_ConfusionImg, &ui_img_confusion_png);
    lv_obj_set_width(ui_ConfusionImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfusionImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConfusionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfusionImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ConfusionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CoolnessImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_CoolnessImg, &ui_img_coolness_png);
    lv_obj_set_width(ui_CoolnessImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoolnessImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CoolnessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CoolnessImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CoolnessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CryingImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_CryingImg, &ui_img_crying_png);
    lv_obj_set_width(ui_CryingImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CryingImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CryingImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CryingImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CryingImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DeliciousnessImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_DeliciousnessImg, &ui_img_deliciousness_png);
    lv_obj_set_width(ui_DeliciousnessImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeliciousnessImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DeliciousnessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeliciousnessImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DeliciousnessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DescriptionImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_DescriptionImg, &ui_img_description_png);
    lv_obj_set_width(ui_DescriptionImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DescriptionImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DescriptionImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DescriptionImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DescriptionImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DrowsinessImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_DrowsinessImg, &ui_img_drowsiness_png);
    lv_obj_set_width(ui_DrowsinessImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DrowsinessImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DrowsinessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DrowsinessImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_DrowsinessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EmbarrassmeImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_EmbarrassmeImg, &ui_img_embarrassment_png);
    lv_obj_set_width(ui_EmbarrassmeImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EmbarrassmeImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_EmbarrassmeImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EmbarrassmeImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_EmbarrassmeImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FunnyImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_FunnyImg, &ui_img_funny_png);
    lv_obj_set_width(ui_FunnyImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FunnyImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FunnyImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FunnyImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FunnyImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HappinessImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_HappinessImg, &ui_img_happiness_png);
    lv_obj_set_width(ui_HappinessImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HappinessImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HappinessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HappinessImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HappinessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InterestImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_InterestImg, &ui_img_interest_png);
    lv_obj_set_width(ui_InterestImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InterestImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_InterestImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_InterestImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_InterestImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KissImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_KissImg, &ui_img_kiss_png);
    lv_obj_set_width(ui_KissImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KissImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_KissImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KissImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_KissImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LaughHeartilyImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_LaughHeartilyImg, &ui_img_embarrassment_png);
    lv_obj_set_width(ui_LaughHeartilyImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaughHeartilyImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LaughHeartilyImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LaughHeartilyImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LaughHeartilyImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ListeningImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_ListeningImg, &ui_img_listening_png);
    lv_obj_set_width(ui_ListeningImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ListeningImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ListeningImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ListeningImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ListeningImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LoveImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_LoveImg, &ui_img_love_png);
    lv_obj_set_width(ui_LoveImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoveImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LoveImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LoveImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LoveImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NeutralityImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_NeutralityImg, &ui_img_neutrality_png);
    lv_obj_set_width(ui_NeutralityImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NeutralityImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NeutralityImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NeutralityImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NeutralityImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RelaxImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_RelaxImg, &ui_img_relax_png);
    lv_obj_set_width(ui_RelaxImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RelaxImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RelaxImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RelaxImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RelaxImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SadnessImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_SadnessImg, &ui_img_sadness_png);
    lv_obj_set_width(ui_SadnessImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SadnessImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SadnessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SadnessImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SadnessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShockImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_ShockImg, &ui_img_shock_png);
    lv_obj_set_width(ui_ShockImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShockImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShockImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShockImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ShockImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SleepyImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_SleepyImg, &ui_img_sleepy_png);
    lv_obj_set_width(ui_SleepyImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SleepyImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SleepyImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SleepyImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SleepyImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SpeechImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_SpeechImg, &ui_img_speech_png);
    lv_obj_set_width(ui_SpeechImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpeechImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SpeechImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeechImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SpeechImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StupidityImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_StupidityImg, &ui_img_stupidity_png);
    lv_obj_set_width(ui_StupidityImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StupidityImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StupidityImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StupidityImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_StupidityImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ThinkingImg = lv_img_create(ui_AIExpressionImg);
    lv_img_set_src(ui_ThinkingImg, &ui_img_thinking_png);
    lv_obj_set_width(ui_ThinkingImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThinkingImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThinkingImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ThinkingImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ThinkingImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatLabCont2 = lv_obj_create(ui_AIChat);
    lv_obj_remove_style_all(ui_AIChatLabCont2);
    lv_obj_set_width(ui_AIChatLabCont2, 230);
    lv_obj_set_height(ui_AIChatLabCont2, 235);
    lv_obj_set_x(ui_AIChatLabCont2, 0);
    lv_obj_set_y(ui_AIChatLabCont2, 25);
    lv_obj_set_align(ui_AIChatLabCont2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatLabCont2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_AIChatLabCont2);
    lv_obj_set_width(ui_Label2, 230);
    lv_obj_set_height(ui_Label2, 142);
    lv_label_set_long_mode(ui_Label2, LV_LABEL_LONG_WRAP);
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 20);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, 0);
    lv_label_set_text(ui_Label2, "Standby");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_AIChatLabCont2);
    lv_img_set_src(ui_Image6, &ui_img_lv2_ai_dialogue_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image6, 0);
    lv_obj_set_y(ui_Image6, 5);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AIChatReturnBtn, ui_event_AIChatReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIChatVolumBtn2, ui_event_AIChatVolumBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIChatLabCont, ui_event_Img6, LV_EVENT_ALL, NULL);

}

void ui_AIChat_screen_destroy(void)
{
    if(ui_AIChat) lv_obj_del(ui_AIChat);                            

    // NULL screen variables
    ui_AIChat = NULL;
    ui_AIChatTitleCont = NULL;
    ui_AIChatReturnImg = NULL;
    ui_AIChatTitleLab = NULL;
    ui_AIChatReturnBtn = NULL;
    ui_AIChatVolumBtn2 = NULL;
    ui_AIChatVolumImg3 = NULL;
    ui_AIChatVolumImg2 = NULL;
    ui_AIChatVolumImg1 = NULL;
    ui_AIChatVolumImg0 = NULL;
    ui_AIChatLabCont = NULL;
    ui_AIExpressionImg = NULL;
    ui_AngerImg = NULL;
    ui_BlinkingImg = NULL;
    ui_ConfidenceImg = NULL;
    ui_ConfusionImg = NULL;
    ui_CoolnessImg = NULL;
    ui_CryingImg = NULL;
    ui_DeliciousnessImg = NULL;
    ui_DescriptionImg = NULL;
    ui_DrowsinessImg = NULL;
    ui_EmbarrassmeImg = NULL;
    ui_FunnyImg = NULL;
    ui_HappinessImg = NULL;
    ui_InterestImg = NULL;
    ui_KissImg = NULL;
    ui_LaughHeartilyImg = NULL;
    ui_ListeningImg = NULL;
    ui_LoveImg = NULL;
    ui_NeutralityImg = NULL;
    ui_RelaxImg = NULL;
    ui_SadnessImg = NULL;
    ui_ShockImg = NULL;
    ui_SleepyImg = NULL;
    ui_SpeechImg = NULL;
    ui_StupidityImg = NULL;
    ui_ThinkingImg = NULL;
    ui_AIChatLabCont2 = NULL;
    ui_Label2 = NULL;
    ui_Image6 = NULL;

}
