// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_NetworkConfigure = NULL;
lv_obj_t * ui_NetworkConfigureTitleCont = NULL;
lv_obj_t * ui_NetworkConfigureReturnImg = NULL;
lv_obj_t * ui_NetworkConfigureTitleLab = NULL;
lv_obj_t * ui_NetworkConfigureReturnBtn = NULL;
lv_obj_t * ui_NetworkConfigureCont = NULL;
lv_obj_t * ui_NetworkConfigureLab = NULL;
lv_obj_t * ui_NetworkConfigureBtn = NULL;
lv_obj_t * ui_NetworkConfigureBtnLab = NULL;
lv_obj_t * ui_NetworkConfigureName = NULL;
// event funtions
void ui_event_NetworkConfigureReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
    }
}

void ui_event_NetworkConfigureBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
       reconfigure_btn = true;
    }
}

// build funtions

void ui_NetworkConfigure_screen_init(void)
{
    char labelText[16];
    ui_NetworkConfigure = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_NetworkConfigure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NetworkConfigure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkConfigure, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureTitleCont = lv_obj_create(ui_NetworkConfigure);
    lv_obj_remove_style_all(ui_NetworkConfigureTitleCont);
    lv_obj_set_width(ui_NetworkConfigureTitleCont, 240);
    lv_obj_set_height(ui_NetworkConfigureTitleCont, 50);
    lv_obj_set_x(ui_NetworkConfigureTitleCont, 0);
    lv_obj_set_y(ui_NetworkConfigureTitleCont, -117);
    lv_obj_set_align(ui_NetworkConfigureTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NetworkConfigureTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NetworkConfigureTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkConfigureTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureReturnImg = lv_img_create(ui_NetworkConfigureTitleCont);
    lv_img_set_src(ui_NetworkConfigureReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_NetworkConfigureReturnImg, 20);
    lv_obj_set_height(ui_NetworkConfigureReturnImg, 20);
    lv_obj_set_x(ui_NetworkConfigureReturnImg, -85);
    lv_obj_set_y(ui_NetworkConfigureReturnImg, 0);
    lv_obj_set_align(ui_NetworkConfigureReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NetworkConfigureReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_NetworkConfigureReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NetworkConfigureTitleLab = lv_label_create(ui_NetworkConfigureTitleCont);
    lv_obj_set_width(ui_NetworkConfigureTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkConfigureTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetworkConfigureTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkConfigureTitleLab, "Configure Network");
    lv_obj_set_style_text_color(ui_NetworkConfigureTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkConfigureTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkConfigureTitleLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureReturnBtn = lv_btn_create(ui_NetworkConfigureTitleCont);
    lv_obj_set_width(ui_NetworkConfigureReturnBtn, 100);
    lv_obj_set_height(ui_NetworkConfigureReturnBtn, 50);
    lv_obj_set_x(ui_NetworkConfigureReturnBtn, -70);
    lv_obj_set_y(ui_NetworkConfigureReturnBtn, 0);
    lv_obj_set_align(ui_NetworkConfigureReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_NetworkConfigureReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkConfigureReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NetworkConfigureReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NetworkConfigureReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureCont = lv_obj_create(ui_NetworkConfigure);
    lv_obj_remove_style_all(ui_NetworkConfigureCont);
    lv_obj_set_width(ui_NetworkConfigureCont, 220);
    lv_obj_set_height(ui_NetworkConfigureCont, 220);
    lv_obj_set_x(ui_NetworkConfigureCont, 0);
    lv_obj_set_y(ui_NetworkConfigureCont, 26);
    lv_obj_set_align(ui_NetworkConfigureCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NetworkConfigureCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NetworkConfigureCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkConfigureCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureLab = lv_label_create(ui_NetworkConfigureCont);
    lv_obj_set_width(ui_NetworkConfigureLab, 210);
    lv_obj_set_height(ui_NetworkConfigureLab, 220);
    lv_obj_set_align(ui_NetworkConfigureLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkConfigureLab,
                      "Connect your phone to the Wi-Fi hotspot:\n\n\nIf the webpage does not open automatically,\nplease visit http://192.168.4.1\n\nTo reconfigure the network,tap the button below.");
    lv_obj_set_style_text_color(ui_NetworkConfigureLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkConfigureLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkConfigureLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureBtn = lv_btn_create(ui_NetworkConfigureCont);
    lv_obj_set_width(ui_NetworkConfigureBtn, 140);
    lv_obj_set_height(ui_NetworkConfigureBtn, 30);
    lv_obj_set_x(ui_NetworkConfigureBtn, 0);
    lv_obj_set_y(ui_NetworkConfigureBtn, 85);
    lv_obj_set_align(ui_NetworkConfigureBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_NetworkConfigureBtn, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NetworkConfigureBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkConfigureBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkConfigureBtnLab = lv_label_create(ui_NetworkConfigureBtn);
    lv_obj_set_width(ui_NetworkConfigureBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkConfigureBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_NetworkConfigureBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkConfigureBtnLab, "RECONFIGURE");
    lv_obj_set_style_text_font(ui_NetworkConfigureBtnLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    
    ui_NetworkConfigureName = lv_label_create(ui_NetworkConfigureCont);
    lv_obj_set_width(ui_NetworkConfigureName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkConfigureName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkConfigureName, -0);
    lv_obj_set_y(ui_NetworkConfigureName, -60);
    lv_obj_set_align(ui_NetworkConfigureName, LV_ALIGN_CENTER);
    //snprintf(ui_NetworkConfigureName, sizeof(ui_NetworkConfigureName), ssidstr_c);
    lv_label_set_text(ui_NetworkConfigureName, ssidstr_c);
    lv_obj_set_style_text_color(ui_NetworkConfigureName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkConfigureName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkConfigureName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_NetworkConfigureBtn, ui_event_NetworkConfigureBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NetworkConfigureReturnBtn, ui_event_NetworkConfigureReturnBtn, LV_EVENT_ALL, NULL);

}

void ui_NetworkConfigure_screen_destroy(void)
{
    if(ui_NetworkConfigure) lv_obj_del(ui_NetworkConfigure);

    // NULL screen variables
    ui_NetworkConfigure = NULL;
    ui_NetworkConfigureTitleCont = NULL;
    ui_NetworkConfigureReturnImg = NULL;
    ui_NetworkConfigureTitleLab = NULL;
    ui_NetworkConfigureReturnBtn = NULL;
    ui_NetworkConfigureCont = NULL;
    ui_NetworkConfigureLab = NULL;
    ui_NetworkConfigureBtn = NULL;
    ui_NetworkConfigureBtnLab = NULL;
    ui_NetworkConfigureName = NULL;

}
