// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_RGBLIGHT_H
#define UI_RGBLIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RGBLight
extern void ui_RGBLight_screen_init(void);
extern void ui_RGBLight_screen_destroy(void);
extern lv_obj_t * ui_RGBLight;
extern lv_obj_t * ui_RGBLightTitleCont;
extern lv_obj_t * ui_RGBLightReturnImg;
extern lv_obj_t * ui_RGBLightTitleLab;
extern void ui_event_RGBLightReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_RGBLightReturnBtn;
extern lv_obj_t * ui_RGBLightFunctionCont;
extern lv_obj_t * ui_RGBLightSelectLab;
extern lv_obj_t * ui_RGBLightSelectOpenBtn;
extern lv_obj_t * ui_RGBLightSelectOpenLab;
extern lv_obj_t * ui_RGBLightCloseBtn;
extern lv_obj_t * ui_RGBLightCloseLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

