// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SHOTDOWNSCR_H
#define UI_SHOTDOWNSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ShotdownScr
extern void ui_ShotdownScr_screen_init(void);
extern void ui_ShotdownScr_screen_destroy(void);
extern lv_obj_t * ui_ShotdownScr;
extern lv_obj_t * ui_PoweroffTitleCont;
extern lv_obj_t * ui_PoweroffReturnImg;
extern lv_obj_t * ui_PoweroffTitleLab;
extern void ui_event_PoweroffReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_PoweroffReturnBtn;
extern lv_obj_t * ui_PoweroffSlider;
extern lv_obj_t * ui_PoweroffLab;
extern lv_obj_t * ui_PoweroffSrcRssi0;
extern lv_obj_t * ui_PoweroffSrcRssi1;
extern lv_obj_t * ui_PoweroffSrcRssi2;
extern lv_obj_t * ui_PoweroffSrcRssi3;
extern lv_obj_t * ui_PoweroffSrcRssi4;
extern lv_obj_t * ui_PoweroffSrcRssi5;
extern lv_obj_t * ui_PoweroffWiFiCont;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

