// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SettingScr = NULL;
lv_obj_t * ui_SettingEntryImg = NULL;
lv_obj_t * ui_SettingPageIndexDot1 = NULL;
lv_obj_t * ui_SettingPageIndexDot0 = NULL;
lv_obj_t * ui_SettingPageIndexDot2 = NULL;
lv_obj_t * ui_SettingSrcWiFiCont = NULL;
lv_obj_t * ui_SettingSrcRssi5 = NULL;
lv_obj_t * ui_SettingSrcRssi4 = NULL;
lv_obj_t * ui_SettingSrcRssi3 = NULL;
lv_obj_t * ui_SettingSrcRssi2 = NULL;
lv_obj_t * ui_SettingSrcRssi1 = NULL;
lv_obj_t * ui_SettingSrcRssi0 = NULL;
lv_obj_t * ui_SettingSrcLab = NULL;
lv_obj_t * ui_SettingTopCont = NULL;
// event funtions
void ui_event_SettingScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AIChatSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatSrc_screen_init);
    }
}

// void ui_event_SettingEntryImg(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
//     }
// }
void ui_event_SettingEntryImg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t * indev = lv_indev_get_act();

    static lv_point_t press_point;

    if(event_code == LV_EVENT_PRESSED)
    {
        // 记录按下坐标
        lv_indev_get_point(indev, &press_point);
    }
    else if(event_code == LV_EVENT_RELEASED)
    {
        lv_point_t release_point;
        lv_indev_get_point(indev, &release_point);

        int dx = release_point.x - press_point.x;
        int dy = release_point.y - press_point.y;

        /* ---------- 滑动过滤 ---------- */
        if(LV_ABS(dx) > SLIDE_THRESHOLD &&
           LV_ABS(dx) > LV_ABS(dy))
        {
            // 横向滑动，吞掉点击
            return;
        }

        /* ---------- 原来的点击逻辑 ---------- */
        _ui_screen_change(&ui_SettingSrcMenu,
                          LV_SCR_LOAD_ANIM_FADE_ON,
                          0, 0,
                          &ui_SettingSrcMenu_screen_init);
    }
}
// build funtions

void ui_SettingScr_screen_init(void)
{
    ui_SettingScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingScr, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingEntryImg = lv_imgbtn_create(ui_SettingScr);
    lv_imgbtn_set_src(ui_SettingEntryImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lv2_ai_setting_png, NULL);
    lv_imgbtn_set_src(ui_SettingEntryImg, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lv2_ai_setting_png, NULL);
    lv_obj_set_width(ui_SettingEntryImg, 160);
    lv_obj_set_height(ui_SettingEntryImg, 100);
    lv_obj_set_align(ui_SettingEntryImg, LV_ALIGN_CENTER);

    ui_SettingPageIndexDot1 = lv_btn_create(ui_SettingScr);
    lv_obj_set_width(ui_SettingPageIndexDot1, 8);
    lv_obj_set_height(ui_SettingPageIndexDot1, 8);
    lv_obj_set_x(ui_SettingPageIndexDot1, 0);
    lv_obj_set_y(ui_SettingPageIndexDot1, 100);
    lv_obj_set_align(ui_SettingPageIndexDot1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingPageIndexDot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPageIndexDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingPageIndexDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingPageIndexDot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingPageIndexDot0 = lv_btn_create(ui_SettingScr);
    lv_obj_set_width(ui_SettingPageIndexDot0, 8);
    lv_obj_set_height(ui_SettingPageIndexDot0, 8);
    lv_obj_set_x(ui_SettingPageIndexDot0, -30);
    lv_obj_set_y(ui_SettingPageIndexDot0, 100);
    lv_obj_set_align(ui_SettingPageIndexDot0, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingPageIndexDot0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPageIndexDot0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingPageIndexDot0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingPageIndexDot0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingPageIndexDot2 = lv_btn_create(ui_SettingScr);
    lv_obj_set_width(ui_SettingPageIndexDot2, 8);
    lv_obj_set_height(ui_SettingPageIndexDot2, 8);
    lv_obj_set_x(ui_SettingPageIndexDot2, 30);
    lv_obj_set_y(ui_SettingPageIndexDot2, 100);
    lv_obj_set_align(ui_SettingPageIndexDot2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingPageIndexDot2, lv_color_hex(0x07F734), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingPageIndexDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingPageIndexDot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingPageIndexDot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingTopCont = lv_obj_create(ui_SettingScr);
    lv_obj_remove_style_all(ui_SettingTopCont);
    lv_obj_set_width(ui_SettingTopCont, 240);
    lv_obj_set_height(ui_SettingTopCont, 50);
    lv_obj_set_x(ui_SettingTopCont, 0);
    lv_obj_set_y(ui_SettingTopCont, -117);
    lv_obj_set_align(ui_SettingTopCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingTopCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingTopCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingTopCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcLab = lv_label_create(ui_SettingTopCont);
    lv_obj_set_height(ui_SettingSrcLab, 20);
    lv_obj_set_width(ui_SettingSrcLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_SettingSrcLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingSrcLab, "Setting");
    lv_obj_set_style_text_color(ui_SettingSrcLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingSrcLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingSrcLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcWiFiCont = lv_obj_create(ui_SettingTopCont);
    lv_obj_remove_style_all(ui_SettingSrcWiFiCont);
    lv_obj_set_width(ui_SettingSrcWiFiCont, 20);
    lv_obj_set_height(ui_SettingSrcWiFiCont, 20);
    lv_obj_set_x(ui_SettingSrcWiFiCont, 85);
    lv_obj_set_y(ui_SettingSrcWiFiCont, 0);
    lv_obj_set_align(ui_SettingSrcWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingSrcWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi5 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_SettingSrcRssi5, 20);
    lv_obj_set_height(ui_SettingSrcRssi5, 20);
    lv_obj_set_align(ui_SettingSrcRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi4 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_SettingSrcRssi4, 20);
    lv_obj_set_height(ui_SettingSrcRssi4, 20);
    lv_obj_set_align(ui_SettingSrcRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi3 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_SettingSrcRssi3, 20);
    lv_obj_set_height(ui_SettingSrcRssi3, 20);
    lv_obj_set_align(ui_SettingSrcRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi2 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_SettingSrcRssi2, 20);
    lv_obj_set_height(ui_SettingSrcRssi2, 20);
    lv_obj_set_align(ui_SettingSrcRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi1 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_SettingSrcRssi1, 20);
    lv_obj_set_height(ui_SettingSrcRssi1, 20);
    lv_obj_set_align(ui_SettingSrcRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcRssi0 = lv_img_create(ui_SettingSrcWiFiCont);
    lv_img_set_src(ui_SettingSrcRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_SettingSrcRssi0, 20);
    lv_obj_set_height(ui_SettingSrcRssi0, 20);
    lv_obj_set_align(ui_SettingSrcRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcRssi0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_SettingEntryImg, ui_event_SettingEntryImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingScr, ui_event_SettingScr, LV_EVENT_ALL, NULL);

}

void ui_SettingScr_screen_destroy(void)
{
    if(ui_SettingScr) lv_obj_del(ui_SettingScr);

    // NULL screen variables
    ui_SettingScr = NULL;
    ui_SettingEntryImg = NULL;
    ui_SettingPageIndexDot1 = NULL;
    ui_SettingPageIndexDot0 = NULL;
    ui_SettingPageIndexDot2 = NULL;
    ui_SettingSrcWiFiCont = NULL;
    ui_SettingSrcRssi5 = NULL;
    ui_SettingSrcRssi4 = NULL;
    ui_SettingSrcRssi3 = NULL;
    ui_SettingSrcRssi2 = NULL;
    ui_SettingSrcRssi1 = NULL;
    ui_SettingSrcRssi0 = NULL;
    ui_SettingSrcLab = NULL;
    ui_SettingTopCont = NULL;
}
