#include "class/hid/hid.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ServerConnectSrc = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ServerConnectBtn = NULL;
lv_obj_t * ui_WiFiNoConnectBtnLab2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_ServerConnectSpinner = NULL;
// event funtions
void ui_event_ui_ServerConnectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
      if(screen_index == 0)
      {
        //device_active_steup = 0;
        end_active = true;
        lv_obj_add_flag(ui_Label5, LV_OBJ_FLAG_HIDDEN);
        if(current_active_screen == 3)
        {
          _ui_screen_change(&ui_AIRecognitionExitScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionExitScr_screen_init);
        }
        else{
          _ui_screen_change(&ui_AIChatExitScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatExitScr_screen_init);
        }
        
      }
       
    }
}

// build funtions

void ui_ServerConnectSrc_screen_init(void)
{
    ui_ServerConnectSrc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ServerConnectSrc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ServerConnectSrc, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServerConnectSrc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_ServerConnectSrc);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 240);
    lv_obj_set_height(ui_Container4, 284);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Label4, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(ui_Label4, "Opening HTTP Connextion to\n\"https://api.tenclass.net/\nxiaozhi/ota/");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServerConnectBtn = lv_btn_create(ui_ServerConnectSrc);
    lv_obj_set_width(ui_ServerConnectBtn, 160);
    lv_obj_set_height(ui_ServerConnectBtn, 30);
    lv_obj_set_x(ui_ServerConnectBtn, 0);
    lv_obj_set_y(ui_ServerConnectBtn, 50);
    lv_obj_set_align(ui_ServerConnectBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ServerConnectBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ServerConnectBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServerConnectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ServerConnectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ServerConnectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNoConnectBtnLab2 = lv_label_create(ui_ServerConnectBtn);
    lv_obj_set_width(ui_WiFiNoConnectBtnLab2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNoConnectBtnLab2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiNoConnectBtnLab2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNoConnectBtnLab2, "Cancel");
    lv_obj_set_style_text_font(ui_WiFiNoConnectBtnLab2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_ServerConnectSrc);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 20);
    lv_obj_add_flag(ui_Label5, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "123445");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x09F138), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ServerConnectSpinner = lv_spinner_create(ui_Container4, 1000, 90);
    lv_obj_set_width(ui_ServerConnectSpinner, 48);
    lv_obj_set_height(ui_ServerConnectSpinner, 48);
    lv_obj_set_x(ui_ServerConnectSpinner, 3);
    lv_obj_set_y(ui_ServerConnectSpinner, -2);
    lv_obj_set_align(ui_ServerConnectSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ServerConnectSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ServerConnectSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ServerConnectSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ServerConnectSpinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ServerConnectSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_ServerConnectSpinner, &ui_img_loading_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
  
    lv_obj_add_event_cb(ui_ServerConnectBtn, ui_event_ui_ServerConnectBtn, LV_EVENT_ALL, NULL);
}

void ui_ServerConnectSrc_screen_destroy(void)
{
    if(ui_ServerConnectSrc) lv_obj_del(ui_ServerConnectSrc);

    // NULL screen variables
    ui_ServerConnectSrc = NULL;
    ui_Container4 = NULL;
    ui_Label4 = NULL;
    ui_ServerConnectBtn = NULL;
    ui_WiFiNoConnectBtnLab2 = NULL;
    ui_Label5 = NULL;
    ui_ServerConnectSpinner = NULL;

}
