// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SplashScr = NULL;
lv_obj_t * ui_SplashScrImg = NULL;
// event funtions
void static delete_splash_timer_cb(lv_timer_t * t) {
    ui_SplashScr_screen_destroy(); // 调用你写好的销毁函数
}
void ui_event_SplashScr(lv_timer_t * timer)
{

        if(restartFlag == true)
        {
            _ui_screen_change(&ui_WiFiNoConnectSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WiFiNoConnectSrc_screen_init);
            
        }
        else
        {
            _ui_screen_change(&ui_AIRecognitionScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionScr_screen_init);
           
        }
        lv_timer_del(timer);
        ui_SplashScr_screen_destroy();
}

// build funtions

void ui_SplashScr_screen_init(void)
{
    ui_SplashScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashScrImg = lv_img_create(ui_SplashScr);
    lv_img_set_src(ui_SplashScrImg, &ui_img_elecrow_logo_png);
    lv_obj_set_width(ui_SplashScrImg, 100);
    lv_obj_set_height(ui_SplashScrImg, 95);
    lv_obj_set_align(ui_SplashScrImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SplashScrImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SplashScrImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    //lv_obj_add_event_cb(ui_SplashScr, ui_event_SplashScr, LV_EVENT_ALL, NULL);
    lv_timer_create(ui_event_SplashScr, 2000, NULL);
}

void ui_SplashScr_screen_destroy(void)
{
    if(ui_SplashScr) lv_obj_del(ui_SplashScr);

    // NULL screen variables
    ui_SplashScr = NULL;
    ui_SplashScrImg = NULL;

}
