// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_WiFiNetwork = NULL;
lv_obj_t * ui_WiFiNetworkTitleCont = NULL;
lv_obj_t * ui_WiFiNetworkReturnImg = NULL;
lv_obj_t * ui_WiFiNetworkTitleLab = NULL;
lv_obj_t * ui_WiFiNetworkReturnBtn = NULL;
lv_obj_t * ui_WiFiNetworkFunctionCont = NULL;
lv_obj_t * ui_WiFiNetworkLab = NULL;
lv_obj_t * ui_WiFiNetworName = NULL;
// event funtions
void ui_event_WiFiNetworkReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
    }
}

// build funtions

void ui_WiFiNetwork_screen_init(void)
{
    ui_WiFiNetwork = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiNetwork, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkTitleCont = lv_obj_create(ui_WiFiNetwork);
    lv_obj_remove_style_all(ui_WiFiNetworkTitleCont);
    lv_obj_set_width(ui_WiFiNetworkTitleCont, 240);
    lv_obj_set_height(ui_WiFiNetworkTitleCont, 50);
    lv_obj_set_x(ui_WiFiNetworkTitleCont, 0);
    lv_obj_set_y(ui_WiFiNetworkTitleCont, -117);
    lv_obj_set_align(ui_WiFiNetworkTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFiNetworkTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiNetworkTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNetworkTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkReturnImg = lv_img_create(ui_WiFiNetworkTitleCont);
    lv_img_set_src(ui_WiFiNetworkReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_WiFiNetworkReturnImg, 20);
    lv_obj_set_height(ui_WiFiNetworkReturnImg, 20);
    lv_obj_set_x(ui_WiFiNetworkReturnImg, -85);
    lv_obj_set_y(ui_WiFiNetworkReturnImg, 0);
    lv_obj_set_align(ui_WiFiNetworkReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiNetworkReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiNetworkReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiNetworkTitleLab = lv_label_create(ui_WiFiNetworkTitleCont);
    lv_obj_set_width(ui_WiFiNetworkTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNetworkTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiNetworkTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNetworkTitleLab, "WiFi Network");
    lv_obj_set_style_text_color(ui_WiFiNetworkTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiNetworkTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiNetworkTitleLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkReturnBtn = lv_btn_create(ui_WiFiNetworkTitleCont);
    lv_obj_set_width(ui_WiFiNetworkReturnBtn, 100);
    lv_obj_set_height(ui_WiFiNetworkReturnBtn, 50);
    lv_obj_set_x(ui_WiFiNetworkReturnBtn, -70);
    lv_obj_set_y(ui_WiFiNetworkReturnBtn, 0);
    lv_obj_set_align(ui_WiFiNetworkReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_WiFiNetworkReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNetworkReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WiFiNetworkReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WiFiNetworkReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkFunctionCont = lv_obj_create(ui_WiFiNetwork);
    lv_obj_remove_style_all(ui_WiFiNetworkFunctionCont);
    lv_obj_set_width(ui_WiFiNetworkFunctionCont, 220);
    lv_obj_set_height(ui_WiFiNetworkFunctionCont, 160);
    lv_obj_set_align(ui_WiFiNetworkFunctionCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFiNetworkFunctionCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiNetworkFunctionCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNetworkFunctionCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkLab = lv_label_create(ui_WiFiNetworkFunctionCont);
    lv_obj_set_width(ui_WiFiNetworkLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNetworkLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiNetworkLab, 0);
    lv_obj_set_y(ui_WiFiNetworkLab, -35);
    lv_obj_set_align(ui_WiFiNetworkLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNetworkLab, "Current Connect WiFi:");
    lv_obj_set_style_text_color(ui_WiFiNetworkLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiNetworkLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiNetworkLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworName = lv_label_create(ui_WiFiNetworkFunctionCont);
    lv_obj_set_width(ui_WiFiNetworName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNetworName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiNetworName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNetworName, "No Connection");
    lv_obj_set_style_text_color(ui_WiFiNetworName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiNetworName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiNetworName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WiFiNetworkReturnBtn, ui_event_WiFiNetworkReturnBtn, LV_EVENT_ALL, NULL);

}

void ui_WiFiNetwork_screen_destroy(void)
{
    if(ui_WiFiNetwork) lv_obj_del(ui_WiFiNetwork);

    // NULL screen variables
    ui_WiFiNetwork = NULL;
    ui_WiFiNetworkTitleCont = NULL;
    ui_WiFiNetworkReturnImg = NULL;
    ui_WiFiNetworkTitleLab = NULL;
    ui_WiFiNetworkReturnBtn = NULL;
    ui_WiFiNetworkFunctionCont = NULL;
    ui_WiFiNetworkLab = NULL;
    ui_WiFiNetworName = NULL;

}
