// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_WIFINETWORK_H
#define UI_WIFINETWORK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiNetwork
extern void ui_WiFiNetwork_screen_init(void);
extern void ui_WiFiNetwork_screen_destroy(void);
extern lv_obj_t * ui_WiFiNetwork;
extern lv_obj_t * ui_WiFiNetworkTitleCont;
extern lv_obj_t * ui_WiFiNetworkReturnImg;
extern lv_obj_t * ui_WiFiNetworkTitleLab;
extern void ui_event_WiFiNetworkReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_WiFiNetworkReturnBtn;
extern lv_obj_t * ui_WiFiNetworkFunctionCont;
extern lv_obj_t * ui_WiFiNetworkLab;
extern lv_obj_t * ui_WiFiNetworName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

