#include <Arduino.h>
#include <lvgl.h>

#include "src\UI\ui.h"                  // User interface generated by LVGL
#include "src\GFX\LovyanGFX_Driver.h"   // LovyanGFX display driver
#include "src\AW9523\elecrow_aw9523.h"  // AW9523 I2C GPIO/LED expander

// I2C pins for AW9523 and potentially other I2C devices
#define I2C_SCL 15
#define I2C_SDA 16

// Screen dimensions
static const uint16_t screenWidth = 240;
static const uint16_t screenHeight = 284;

// LVGL display buffer and driver structures
static lv_disp_draw_buf_t draw_buf;   // Draw buffer structure for LVGL
static lv_disp_drv_t disp_drv;        // Display driver
static lv_indev_drv_t indev_drv;      // Input device driver (touchscreen)

// I2C object
static TwoWire* wi = &Wire;

// ==================== LVGL flush callback ====================
// This function is called by LVGL when a portion of the screen needs to be updated.
// The area parameter contains the rectangle to update, color_p points to pixel data.
void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p) {
  // If a previous DMA or SPI write is still active, finish it
  if (gfx.getStartCount() > 0) {
    gfx.endWrite();
  }

  // Push the new image data using DMA for speed
  gfx.pushImageDMA(
      area->x1, area->y1,                             // Top-left corner
      area->x2 - area->x1 + 1,                        // Width
      area->y2 - area->y1 + 1,                        // Height
      (lgfx::rgb565_t *)&color_p->full                // Pixel buffer (RGB565)
  );

  // Notify LVGL that the flush is complete
  lv_disp_flush_ready(disp);
}

// ==================== Touchscreen read callback ====================
// This function is called periodically by LVGL to read touch status
uint16_t touchX, touchY;
void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data) {
  data->state = LV_INDEV_STATE_REL;   // Default: no touch
  if (gfx.getTouch(&touchX, &touchY)) { // Read touch coordinates
    data->state = LV_INDEV_STATE_PR;   // Touch detected
    data->point.x = 240 - touchX;      // Adjust X coordinate if needed (flip horizontally)
    data->point.y = touchY + 10;       // Adjust Y coordinate if needed (offset)
  }
}

// ==================== Arduino setup ====================
void setup(void)
{
  // Initialize I2C communication on user-defined pins
  wi->setPins(I2C_SDA, I2C_SCL);
  wi->begin();
  delay(100);  // Short delay to stabilize I2C

  // Initialize AW9523 I2C GPIO/LED expander
  aw9523.AW_init();           // Initialize chip
  aw9523.AW_set_POWER(true);  // Enable the power domain
  aw9523.AW_set_lcd_blight(100); // Set LCD backlight (0-100%)

  // Initialize LovyanGFX display driver
  gfx.init();      // Initialize SPI/I2C hardware
  gfx.initDMA();   // Enable DMA acceleration
  gfx.startWrite();  // Start display write session
  gfx.fillScreen(TFT_BLACK); // Clear screen to black

  // Initialize LVGL library
  lv_init();

  // Allocate LVGL display buffers in PSRAM to support large screen
  size_t buffer_size = sizeof(lv_color_t) * screenWidth * screenHeight;
  static lv_color_t *buf = (lv_color_t *)heap_caps_malloc(buffer_size, MALLOC_CAP_SPIRAM);
  static lv_color_t *buf1 = (lv_color_t *)heap_caps_malloc(buffer_size, MALLOC_CAP_SPIRAM);

  // Initialize LVGL draw buffer with double buffering
  lv_disp_draw_buf_init(&draw_buf, buf, buf1, screenWidth * screenHeight);

  // Initialize and register LVGL display driver
  lv_disp_drv_init(&disp_drv);
  disp_drv.hor_res = screenWidth;       // Horizontal resolution
  disp_drv.ver_res = screenHeight;      // Vertical resolution
  disp_drv.flush_cb = my_disp_flush;    // Set flush callback
  disp_drv.draw_buf = &draw_buf;        // Assign draw buffer
  lv_disp_drv_register(&disp_drv);      // Register display driver

  // Initialize and register LVGL input device driver for touchscreen
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER; // Pointer device (touch)
  indev_drv.read_cb = my_touchpad_read;   // Touch read callback
  lv_indev_drv_register(&indev_drv);

  // Initialize the user interface (generated by LVGL)
  ui_init();
}

// ==================== Arduino loop ====================
// Main loop only calls LVGL task handler periodically
void loop(void)
{
  lv_timer_handler();  // LVGL task handler updates animations, screen, and input
}
