// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScr_screen_init();
    ui_SettingScr_screen_init();
    ui_SettingSrcMenu_screen_init();//
    ui_ResetToFactory_screen_init();//
    ui_RGBLight_screen_init();//
    ui_SDCard_screen_init();
    ui_ScreenBrightness_screen_init();//
    ui_WiFiNetwork_screen_init();
    //ui_NetworkConfigure_screen_init();//
    ui_AIRecognitionScr_screen_init();
    ui_AIRecognition_screen_init();
    ui_AIRecognitionSave_screen_init();
    ui_AIChatSrc_screen_init();
    ui_AIChatMenu_screen_init();
    ui_AIChat_screen_init();
    ui_ShotdownScr_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScr);
}

void ui_destroy(void)
{
    ui_SplashScr_screen_destroy();
    ui_SettingScr_screen_destroy();
    ui_SettingSrcMenu_screen_destroy();
    ui_ResetToFactory_screen_destroy();
    ui_RGBLight_screen_destroy();
    ui_SDCard_screen_destroy();
    ui_ScreenBrightness_screen_destroy();
    ui_WiFiNetwork_screen_destroy();
    ui_NetworkConfigure_screen_destroy();
    ui_AIRecognitionScr_screen_destroy();
    ui_AIRecognition_screen_destroy();
    ui_AIRecognitionSave_screen_destroy();
    ui_AIChatSrc_screen_destroy();
    ui_AIChatMenu_screen_destroy();
    ui_AIChat_screen_destroy();
    ui_ShotdownScr_screen_destroy();
}
