// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#include "FreeRTOS.h"
#include "task.h"

///////////////////// SCREENS ////////////////////

#include "ui_SplashScr.h"
#include "ui_SettingScr.h"
#include "ui_SettingSrcMenu.h"
#include "ui_ResetToFactory.h"
#include "ui_RGBLight.h"
#include "ui_SDCard.h"
#include "ui_ScreenBrightness.h"
#include "ui_WiFiNetwork.h"
#include "ui_NetworkConfigure.h"
#include "ui_AIRecognitionScr.h"
#include "ui_AIRecognition.h"
#include "ui_AIRecognitionSave.h"
#include "ui_AIChatSrc.h"
#include "ui_AIChatMenu.h"
#include "ui_AIChat.h"
#include "ui_WiFiNoConnectSrc.h"
#include "ui_ServerConnectSrc.h"
#include "ui_VolumSrc.h"
#include "ui_ShotdownScr.h"
#include "ui_AIChatExitScreen.h"
#include "UI_AIRecognitionExitScr.h"

///////////////////// VARIABLES ////////////////////
extern TaskHandle_t video_stream_task_handle;
extern TaskHandle_t activate_task_handle;
extern TaskHandle_t RGB_Light_task_handle;
extern TaskHandle_t SD_Card_task_handle;

extern bool led_status;
extern bool In_AIRecognition_Save_Src;
extern bool img_save_to_sd_flag;
extern bool current_wifi_connected;
extern bool RGBLighCloseSem;
extern bool reconfigure_btn;
extern bool device_active_check;
extern bool aichat_exit;
extern bool AI_Recognition_flag;
extern bool AI_Recognition_exit_flag;
extern bool current_fun_is_Recognition;
extern bool reset_to_factory;
extern bool Touch;
extern bool end_active;
extern bool Power_Off;
extern uint8_t device_active_steup;
extern uint8_t screen_index;
extern uint8_t state;
extern uint8_t brightness_value;
extern uint8_t speaker_value;
extern uint8_t AIChat_Device_Bound_Check;
extern lv_obj_t *camera_output;
extern const char * ssidstr_c;
extern uint8_t current_active_screen;
extern bool restartFlag;
extern uint8_t screen_index;



// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_elecrow_logo_png);    // assets/elecrow_logo.png
LV_IMG_DECLARE(ui_img_lv2_ai_setting_png);    // assets/lv2_ai_setting.png
LV_IMG_DECLARE(ui_img_icon_wifi_link_01_png);    // assets/icon_wifi_link_01.png
LV_IMG_DECLARE(ui_img_icon_wifi_link_02_png);    // assets/icon_wifi_link_02.png
LV_IMG_DECLARE(ui_img_icon_wifi_link_03_png);    // assets/icon_wifi_link_03.png
LV_IMG_DECLARE(ui_img_icon_wifi_link_04_png);    // assets/icon_wifi_link_04.png
LV_IMG_DECLARE(ui_img_icon_wifi_link_05_png);    // assets/icon_wifi_link_05.png
LV_IMG_DECLARE(ui_img_icon_wifi_no_link_01_png);    // assets/icon_wifi_no_link_01.png
LV_IMG_DECLARE(ui_img_icon_return_01_png);    // assets/icon_return_01.png
LV_IMG_DECLARE(ui_img_set_next_step_01_png);    // assets/set_next_step_01.png
LV_IMG_DECLARE(ui_img_icon_sd_card_01_png);    // assets/icon_sd_card_01.png
LV_IMG_DECLARE(ui_img_brightness_plus_png);    // assets/Brightness plus.png
LV_IMG_DECLARE(ui_img_brightness_reduce_png);    // assets/Brightness reduce.png
LV_IMG_DECLARE(ui_img_lv2_ai_photo_png);    // assets/lv2_ai_photo.png
LV_IMG_DECLARE(ui_img_icon_fill_light_off_png);    // assets/icon_fill_light_off.png
LV_IMG_DECLARE(ui_img_icon_fill_light_on_png);    // assets/icon_fill_light_on.png
LV_IMG_DECLARE(ui_img_icon_press_green_png);    // assets/icon_press_green.png
LV_IMG_DECLARE(ui_img_95829391);    // assets/icon_click@2x.png
LV_IMG_DECLARE(ui_img_icon_return_02_png);    // assets/icon_return_02.png
LV_IMG_DECLARE(ui_img_icon_recognition_effect_01_png);    // assets/icon_recognition_effect_01.png
LV_IMG_DECLARE(ui_img_lv2_ai_dialogue_png);    // assets/lv2_ai_dialogue.png
LV_IMG_DECLARE(ui_img_icon_ai_dialogue_server_elecrow_01_png);    // assets/icon_ai_dialogue_server_elecrow_01.png
LV_IMG_DECLARE(ui_img_bj_click_02_png);    // assets/bj_click_02.png
LV_IMG_DECLARE(ui_img_bj_click_01_png);    // assets/bj_click_01.png
LV_IMG_DECLARE(ui_img_icon_ai_dialogue_server_xiaozhi_01_png);    // assets/icon_ai_dialogue_server_xiaozhi_01.png
LV_IMG_DECLARE(ui_img_icon_voice_01_png);    // assets/icon_voice_01.png
LV_IMG_DECLARE(ui_img_icon_voice_02_png);    // assets/icon_voice_02.png
LV_IMG_DECLARE(ui_img_icon_voice_03_png);    // assets/icon_voice_03.png
LV_IMG_DECLARE(ui_img_icon_voice_04_png);    // assets/icon_voice_04.png
LV_IMG_DECLARE(ui_img_icon_set_update_02_png);    // assets/icon_set_update_02.png
LV_IMG_DECLARE(ui_img_anger_png);    // assets/Anger.png
LV_IMG_DECLARE(ui_img_blinking_png);    // assets/Blinking.png
LV_IMG_DECLARE(ui_img_confidence_png);    // assets/Confidence.png
LV_IMG_DECLARE(ui_img_confusion_png);    // assets/Confusion.png
LV_IMG_DECLARE(ui_img_coolness_png);    // assets/Coolness.png
LV_IMG_DECLARE(ui_img_crying_png);    // assets/Crying.png
LV_IMG_DECLARE(ui_img_deliciousness_png);    // assets/Deliciousness.png
LV_IMG_DECLARE(ui_img_description_png);    // assets/Description.png
LV_IMG_DECLARE(ui_img_drowsiness_png);    // assets/Drowsiness.png
LV_IMG_DECLARE(ui_img_embarrassment_png);    // assets/Embarrassment.png
LV_IMG_DECLARE(ui_img_funny_png);    // assets/Funny.png
LV_IMG_DECLARE(ui_img_happiness_png);    // assets/Happiness.png
LV_IMG_DECLARE(ui_img_interest_png);    // assets/Interest.png
LV_IMG_DECLARE(ui_img_kiss_png);    // assets/Kiss.png
LV_IMG_DECLARE(ui_img_listening_png);    // assets/Listening.png
LV_IMG_DECLARE(ui_img_love_png);    // assets/Love.png
LV_IMG_DECLARE(ui_img_neutrality_png);    // assets/Neutrality.png
LV_IMG_DECLARE(ui_img_relax_png);    // assets/Relax.png
LV_IMG_DECLARE(ui_img_sadness_png);    // assets/Sadness.png
LV_IMG_DECLARE(ui_img_shock_png);    // assets/Shock.png
LV_IMG_DECLARE(ui_img_sleepy_png);    // assets/Sleepy.png
LV_IMG_DECLARE(ui_img_speech_png);    // assets/Speech.png
LV_IMG_DECLARE(ui_img_stupidity_png);    // assets/Stupidity.png
LV_IMG_DECLARE(ui_img_thinking_png);    // assets/Thinking.png
LV_IMG_DECLARE(ui_img_loading_png);      //assets/load.png
LV_IMG_DECLARE(ui_img_icon_power_off_png);    // assets/icon_power_off.png

#define SLIDE_THRESHOLD  20 
// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
