// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIChatExitScr = NULL;
lv_obj_t * ui_AIChatExitTitleCont = NULL;
lv_obj_t * ui_AIChatExitReturnImg = NULL;
lv_obj_t * ui_AIChatExitTitleLab = NULL;
lv_obj_t * ui_AIChatExitElEServerCont = NULL;
lv_obj_t * ui_AIChatExitELEImg = NULL;
lv_obj_t * ui_AIChatExitELELab = NULL;
lv_obj_t * ui_AIChatExitELEBtn = NULL;
lv_obj_t * ui_AIChatExitxzCont = NULL;
lv_obj_t * ui_AIChatExitxzLab = NULL;
lv_obj_t * ui_AIChatExitxzImg = NULL;
lv_obj_t * ui_AIChatExitxzBtn = NULL;
lv_obj_t * ui_AIChatExitWiFiCont = NULL;
lv_obj_t * ui_AIChatExitRssi = NULL;
lv_obj_t * ui_AIChatExitCont = NULL;
lv_obj_t * ui_AIChatExitSpinner = NULL;
// event funtions
static void async_destroy_wrapper(void *param)
{
    (void)param; // 不使用参数
    ui_AIChatExitScr_screen_destroy();
}

static void exit_screen_timer_cb(lv_timer_t *timer)
{
  if(current_active_screen == 1 || current_active_screen == 2)
  {
      _ui_screen_change(&ui_AIChatMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatMenu_screen_init);
  }
    
    lv_timer_del(timer);
    lv_async_call(async_destroy_wrapper, NULL);
}
// build funtions

void ui_AIChatExitScr_screen_init(void)
{
    ui_AIChatExitScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIChatExitScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatExitScr, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitTitleCont = lv_obj_create(ui_AIChatExitScr);
    lv_obj_remove_style_all(ui_AIChatExitTitleCont);
    lv_obj_set_width(ui_AIChatExitTitleCont, 240);
    lv_obj_set_height(ui_AIChatExitTitleCont, 50);
    lv_obj_set_x(ui_AIChatExitTitleCont, 0);
    lv_obj_set_y(ui_AIChatExitTitleCont, -117);
    lv_obj_set_align(ui_AIChatExitTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatExitTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitReturnImg = lv_img_create(ui_AIChatExitTitleCont);
    lv_img_set_src(ui_AIChatExitReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_AIChatExitReturnImg, 20);
    lv_obj_set_height(ui_AIChatExitReturnImg, 20);
    lv_obj_set_x(ui_AIChatExitReturnImg, -85);
    lv_obj_set_y(ui_AIChatExitReturnImg, 0);
    lv_obj_set_align(ui_AIChatExitReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatExitReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatExitReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatExitTitleLab = lv_label_create(ui_AIChatExitTitleCont);
    lv_obj_set_width(ui_AIChatExitTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIChatExitTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AIChatExitTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatExitTitleLab, "AI Dialogue");
    lv_obj_set_style_text_color(ui_AIChatExitTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatExitTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChatExitTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitElEServerCont = lv_obj_create(ui_AIChatExitScr);
    lv_obj_remove_style_all(ui_AIChatExitElEServerCont);
    lv_obj_set_width(ui_AIChatExitElEServerCont, 200);
    lv_obj_set_height(ui_AIChatExitElEServerCont, 80);
    lv_obj_set_x(ui_AIChatExitElEServerCont, 0);
    lv_obj_set_y(ui_AIChatExitElEServerCont, -35);
    lv_obj_set_align(ui_AIChatExitElEServerCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitElEServerCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatExitELEImg = lv_imgbtn_create(ui_AIChatExitElEServerCont);
    lv_imgbtn_set_src(ui_AIChatExitELEImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_ai_dialogue_server_elecrow_01_png,
                      NULL);
    lv_obj_set_width(ui_AIChatExitELEImg, 60);
    lv_obj_set_height(ui_AIChatExitELEImg, 60);
    lv_obj_set_x(ui_AIChatExitELEImg, -40);
    lv_obj_set_y(ui_AIChatExitELEImg, 0);
    lv_obj_set_align(ui_AIChatExitELEImg, LV_ALIGN_CENTER);

    ui_AIChatExitELELab = lv_label_create(ui_AIChatExitElEServerCont);
    lv_obj_set_width(ui_AIChatExitELELab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIChatExitELELab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIChatExitELELab, 35);
    lv_obj_set_y(ui_AIChatExitELELab, 0);
    lv_obj_set_align(ui_AIChatExitELELab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatExitELELab, "ELECROW\nServer");
    lv_obj_set_style_text_color(ui_AIChatExitELELab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatExitELELab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
     lv_obj_set_style_text_font(ui_AIChatExitELELab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitELEBtn = lv_btn_create(ui_AIChatExitElEServerCont);
    lv_obj_set_width(ui_AIChatExitELEBtn, 200);
    lv_obj_set_height(ui_AIChatExitELEBtn, 80);
    lv_obj_set_align(ui_AIChatExitELEBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatExitELEBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitELEBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AIChatExitELEBtn, &ui_img_bj_click_02_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatExitELEBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatExitELEBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AIChatExitELEBtn, &ui_img_bj_click_01_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_AIChatExitELEBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_AIChatExitELEBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_AIChatExitxzCont = lv_obj_create(ui_AIChatExitScr);
    lv_obj_remove_style_all(ui_AIChatExitxzCont);
    lv_obj_set_width(ui_AIChatExitxzCont, 200);
    lv_obj_set_height(ui_AIChatExitxzCont, 80);
    lv_obj_set_x(ui_AIChatExitxzCont, 0);
    lv_obj_set_y(ui_AIChatExitxzCont, 65);
    lv_obj_set_align(ui_AIChatExitxzCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitxzCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatExitxzLab = lv_label_create(ui_AIChatExitxzCont);
    lv_obj_set_width(ui_AIChatExitxzLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIChatExitxzLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIChatExitxzLab, 35);
    lv_obj_set_y(ui_AIChatExitxzLab, 0);
    lv_obj_set_align(ui_AIChatExitxzLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatExitxzLab, "Xiaozhi\nServer");
    lv_obj_set_style_text_color(ui_AIChatExitxzLab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatExitxzLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChatExitxzLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitxzImg = lv_imgbtn_create(ui_AIChatExitxzCont);
    lv_imgbtn_set_src(ui_AIChatExitxzImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_ai_dialogue_server_xiaozhi_01_png,
                      NULL);
    lv_obj_set_width(ui_AIChatExitxzImg, 60);
    lv_obj_set_height(ui_AIChatExitxzImg, 60);
    lv_obj_set_x(ui_AIChatExitxzImg, -40);
    lv_obj_set_y(ui_AIChatExitxzImg, 0);
    lv_obj_set_align(ui_AIChatExitxzImg, LV_ALIGN_CENTER);

    ui_AIChatExitxzBtn = lv_btn_create(ui_AIChatExitxzCont);
    lv_obj_set_width(ui_AIChatExitxzBtn, 200);
    lv_obj_set_height(ui_AIChatExitxzBtn, 80);
    lv_obj_set_align(ui_AIChatExitxzBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatExitxzBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitxzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AIChatExitxzBtn, &ui_img_bj_click_02_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatExitxzBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatExitxzBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_AIChatExitxzBtn, &ui_img_bj_click_01_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_AIChatExitWiFiCont = lv_obj_create(ui_AIChatExitScr);
    lv_obj_remove_style_all(ui_AIChatExitWiFiCont);
    lv_obj_set_width(ui_AIChatExitWiFiCont, 20);
    lv_obj_set_height(ui_AIChatExitWiFiCont, 20);
    lv_obj_set_x(ui_AIChatExitWiFiCont, 85);
    lv_obj_set_y(ui_AIChatExitWiFiCont, -117);
    lv_obj_add_flag(ui_AIChatExitWiFiCont, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_AIChatExitWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatExitRssi = lv_img_create(ui_AIChatExitWiFiCont);
    lv_img_set_src(ui_AIChatExitRssi, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_AIChatExitRssi, 20);
    lv_obj_set_height(ui_AIChatExitRssi, 20);
    lv_obj_set_align(ui_AIChatExitRssi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatExitRssi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatExitRssi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatExitCont = lv_obj_create(ui_AIChatExitScr);
    lv_obj_remove_style_all(ui_AIChatExitCont);
    lv_obj_set_width(ui_AIChatExitCont, 240);
    lv_obj_set_height(ui_AIChatExitCont, 284);
    lv_obj_set_align(ui_AIChatExitCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatExitCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitCont, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatExitSpinner = lv_spinner_create(ui_AIChatExitCont, 1000, 90);
    lv_obj_set_width(ui_AIChatExitSpinner, 48);
    lv_obj_set_height(ui_AIChatExitSpinner, 48);
    lv_obj_set_x(ui_AIChatExitSpinner, 3);
    lv_obj_set_y(ui_AIChatExitSpinner, -2);
    lv_obj_set_align(ui_AIChatExitSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatExitSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatExitSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatExitSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AIChatExitSpinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AIChatExitSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_AIChatExitSpinner, &ui_img_loading_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_timer_t *timer = lv_timer_create(exit_screen_timer_cb, 2500, NULL);

}

void ui_AIChatExitScr_screen_destroy(void)
{
    if(ui_AIChatExitScr) lv_obj_del(ui_AIChatExitScr);

    // NULL screen variables
    ui_AIChatExitScr = NULL;
    ui_AIChatExitTitleCont = NULL;
    ui_AIChatExitReturnImg = NULL;
    ui_AIChatExitTitleLab = NULL;
    ui_AIChatExitElEServerCont = NULL;
    ui_AIChatExitELEImg = NULL;
    ui_AIChatExitELELab = NULL;
    ui_AIChatExitELEBtn = NULL;
    ui_AIChatExitxzCont = NULL;
    ui_AIChatExitxzLab = NULL;
    ui_AIChatExitxzImg = NULL;
    ui_AIChatExitxzBtn = NULL;
    ui_AIChatExitWiFiCont = NULL;
    ui_AIChatExitRssi = NULL;
    ui_AIChatExitCont = NULL;
    ui_AIChatExitSpinner = NULL;

}
