// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIChatMenu = NULL;
lv_obj_t * ui_AIChatMenuTitleCont = NULL;
lv_obj_t * ui_AIChatMenuReturnImg = NULL;
lv_obj_t * ui_AIChatMenuTitleLab = NULL;
lv_obj_t * ui_AIChatMenuReturnBtn = NULL;
lv_obj_t * ui_ELEServerCont = NULL;
lv_obj_t * ui_ELEServerContImg = NULL;
lv_obj_t * ui_ELEServerLab = NULL;
lv_obj_t * ui_ELEServerBtn = NULL;
lv_obj_t * ui_XiaozhiServerCont = NULL;
lv_obj_t * ui_XiaozhiServerLab = NULL;
lv_obj_t * ui_XiaozhiServerImg = NULL;
lv_obj_t * ui_XiaozhiServerBtn = NULL;
lv_obj_t * ui_AIChatMenuWiFiCont = NULL;
lv_obj_t * ui_AIChatMenuRssi5 = NULL;
lv_obj_t * ui_AIChatMenuRssi4 = NULL;
lv_obj_t * ui_AIChatMenuRssi3 = NULL;
lv_obj_t * ui_AIChatMenuRssi2 = NULL;
lv_obj_t * ui_AIChatMenuRssi1 = NULL;
lv_obj_t * ui_AIChatMenuRssi0 = NULL;
// event funtions
void ui_event_AIChatMenuReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AIChatSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatSrc_screen_init);
    }
}

void ui_event_AIChatELEServer(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  if(event_code == LV_EVENT_CLICKED)
  {
    AIChat_Device_Bound_Check = 1;

  }
}

void ui_event_AIChatXiaoZhiServer(lv_event_t * e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  if(event_code == LV_EVENT_CLICKED)
  {
    AIChat_Device_Bound_Check = 2;
      
  }
}
// build funtions

void ui_AIChatMenu_screen_init(void)
{
    ui_AIChatMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIChatMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatMenu, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatMenuTitleCont = lv_obj_create(ui_AIChatMenu);
    lv_obj_remove_style_all(ui_AIChatMenuTitleCont);
    lv_obj_set_width(ui_AIChatMenuTitleCont, 240);
    lv_obj_set_height(ui_AIChatMenuTitleCont, 50);
    lv_obj_set_x(ui_AIChatMenuTitleCont, 0);
    lv_obj_set_y(ui_AIChatMenuTitleCont, -117);
    lv_obj_set_align(ui_AIChatMenuTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatMenuTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatMenuTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatMenuTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatMenuReturnImg = lv_img_create(ui_AIChatMenuTitleCont);
    lv_img_set_src(ui_AIChatMenuReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_AIChatMenuReturnImg, 20);
    lv_obj_set_height(ui_AIChatMenuReturnImg, 20);
    lv_obj_set_x(ui_AIChatMenuReturnImg, -85);
    lv_obj_set_y(ui_AIChatMenuReturnImg, 0);
    lv_obj_set_align(ui_AIChatMenuReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuTitleLab = lv_label_create(ui_AIChatMenuTitleCont);
    lv_obj_set_width(ui_AIChatMenuTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIChatMenuTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AIChatMenuTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatMenuTitleLab, "AI Dialogue");
    lv_obj_set_style_text_color(ui_AIChatMenuTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatMenuTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChatMenuTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatMenuReturnBtn = lv_btn_create(ui_AIChatMenuTitleCont);
    lv_obj_set_width(ui_AIChatMenuReturnBtn, 100);
    lv_obj_set_height(ui_AIChatMenuReturnBtn, 50);
    lv_obj_set_x(ui_AIChatMenuReturnBtn, -70);
    lv_obj_set_y(ui_AIChatMenuReturnBtn, 0);
    lv_obj_set_align(ui_AIChatMenuReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatMenuReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatMenuReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatMenuReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatMenuReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ELEServerCont = lv_obj_create(ui_AIChatMenu);
    lv_obj_remove_style_all(ui_ELEServerCont);
    lv_obj_set_width(ui_ELEServerCont, 200);
    lv_obj_set_height(ui_ELEServerCont, 80);
    lv_obj_set_x(ui_ELEServerCont, 0);
    lv_obj_set_y(ui_ELEServerCont, -35);
    lv_obj_set_align(ui_ELEServerCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ELEServerCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ELEServerContImg = lv_imgbtn_create(ui_ELEServerCont);
    lv_imgbtn_set_src(ui_ELEServerContImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_ai_dialogue_server_elecrow_01_png,
                      NULL);
    lv_obj_set_width(ui_ELEServerContImg, 60);
    lv_obj_set_height(ui_ELEServerContImg, 60);
    lv_obj_set_x(ui_ELEServerContImg, -40);
    lv_obj_set_y(ui_ELEServerContImg, 0);
    lv_obj_set_align(ui_ELEServerContImg, LV_ALIGN_CENTER);

    ui_ELEServerLab = lv_label_create(ui_ELEServerCont);
    lv_obj_set_width(ui_ELEServerLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ELEServerLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ELEServerLab, 35);
    lv_obj_set_y(ui_ELEServerLab, 0);
    lv_obj_set_align(ui_ELEServerLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ELEServerLab, "ELECROW\nServer");
    lv_obj_set_style_text_color(ui_ELEServerLab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ELEServerLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ELEServerLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ELEServerBtn = lv_btn_create(ui_ELEServerCont);
    lv_obj_set_width(ui_ELEServerBtn, 200);
    lv_obj_set_height(ui_ELEServerBtn, 80);
    lv_obj_set_align(ui_ELEServerBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ELEServerBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ELEServerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ELEServerBtn, &ui_img_bj_click_02_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ELEServerBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ELEServerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ELEServerBtn, &ui_img_bj_click_01_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_ELEServerBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_ELEServerBtn, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_XiaozhiServerCont = lv_obj_create(ui_AIChatMenu);
    lv_obj_remove_style_all(ui_XiaozhiServerCont);
    lv_obj_set_width(ui_XiaozhiServerCont, 200);
    lv_obj_set_height(ui_XiaozhiServerCont, 80);
    lv_obj_set_x(ui_XiaozhiServerCont, 0);
    lv_obj_set_y(ui_XiaozhiServerCont, 65);
    lv_obj_set_align(ui_XiaozhiServerCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_XiaozhiServerCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XiaozhiServerLab = lv_label_create(ui_XiaozhiServerCont);
    lv_obj_set_width(ui_XiaozhiServerLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XiaozhiServerLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XiaozhiServerLab, 35);
    lv_obj_set_y(ui_XiaozhiServerLab, 0);
    lv_obj_set_align(ui_XiaozhiServerLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XiaozhiServerLab, "Xiaozhi\nServer");
    lv_obj_set_style_text_color(ui_XiaozhiServerLab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XiaozhiServerLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XiaozhiServerLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XiaozhiServerImg = lv_imgbtn_create(ui_XiaozhiServerCont);
    lv_imgbtn_set_src(ui_XiaozhiServerImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_ai_dialogue_server_xiaozhi_01_png,
                      NULL);
    lv_obj_set_width(ui_XiaozhiServerImg, 60);
    lv_obj_set_height(ui_XiaozhiServerImg, 60);
    lv_obj_set_x(ui_XiaozhiServerImg, -40);
    lv_obj_set_y(ui_XiaozhiServerImg, 0);
    lv_obj_set_align(ui_XiaozhiServerImg, LV_ALIGN_CENTER);

    ui_XiaozhiServerBtn = lv_btn_create(ui_XiaozhiServerCont);
    lv_obj_set_width(ui_XiaozhiServerBtn, 200);
    lv_obj_set_height(ui_XiaozhiServerBtn, 80);
    lv_obj_set_align(ui_XiaozhiServerBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_XiaozhiServerBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_XiaozhiServerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_XiaozhiServerBtn, &ui_img_bj_click_02_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_XiaozhiServerBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_XiaozhiServerBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_XiaozhiServerBtn, &ui_img_bj_click_01_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_AIChatMenuWiFiCont = lv_obj_create(ui_AIChatMenu);
    lv_obj_remove_style_all(ui_AIChatMenuWiFiCont);
    lv_obj_set_width(ui_AIChatMenuWiFiCont, 20);
    lv_obj_set_height(ui_AIChatMenuWiFiCont, 20);
    lv_obj_set_x(ui_AIChatMenuWiFiCont, 85);
    lv_obj_set_y(ui_AIChatMenuWiFiCont, -117);
    lv_obj_set_align(ui_AIChatMenuWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatMenuWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi5 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_AIChatMenuRssi5, 20);
    lv_obj_set_height(ui_AIChatMenuRssi5, 20);
    lv_obj_set_align(ui_AIChatMenuRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi4 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_AIChatMenuRssi4, 20);
    lv_obj_set_height(ui_AIChatMenuRssi4, 20);
    lv_obj_set_align(ui_AIChatMenuRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi3 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_AIChatMenuRssi3, 20);
    lv_obj_set_height(ui_AIChatMenuRssi3, 20);
    lv_obj_set_align(ui_AIChatMenuRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi2 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_AIChatMenuRssi2, 20);
    lv_obj_set_height(ui_AIChatMenuRssi2, 20);
    lv_obj_set_align(ui_AIChatMenuRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi1 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_AIChatMenuRssi1, 20);
    lv_obj_set_height(ui_AIChatMenuRssi1, 20);
    lv_obj_set_align(ui_AIChatMenuRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatMenuRssi0 = lv_img_create(ui_AIChatMenuWiFiCont);
    lv_img_set_src(ui_AIChatMenuRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_AIChatMenuRssi0, 20);
    lv_obj_set_height(ui_AIChatMenuRssi0, 20);
    lv_obj_set_align(ui_AIChatMenuRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatMenuRssi0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatMenuRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_AIChatMenuReturnBtn, ui_event_AIChatMenuReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ELEServerBtn, ui_event_AIChatELEServer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_XiaozhiServerBtn, ui_event_AIChatXiaoZhiServer, LV_EVENT_ALL, NULL);

}

void ui_AIChatMenu_screen_destroy(void)
{
    if(ui_AIChatMenu) lv_obj_del(ui_AIChatMenu);

    // NULL screen variables
    ui_AIChatMenu = NULL;
    ui_AIChatMenuTitleCont = NULL;
    ui_AIChatMenuReturnImg = NULL;
    ui_AIChatMenuTitleLab = NULL;
    ui_AIChatMenuReturnBtn = NULL;
    ui_ELEServerCont = NULL;
    ui_ELEServerContImg = NULL;
    ui_ELEServerLab = NULL;
    ui_ELEServerBtn = NULL;
    ui_XiaozhiServerCont = NULL;
    ui_XiaozhiServerLab = NULL;
    ui_XiaozhiServerImg = NULL;
    ui_XiaozhiServerBtn = NULL;
    ui_AIChatMenuWiFiCont = NULL;
    ui_AIChatMenuRssi5 = NULL;
    ui_AIChatMenuRssi4 = NULL;
    ui_AIChatMenuRssi3 = NULL;
    ui_AIChatMenuRssi2 = NULL;
    ui_AIChatMenuRssi1 = NULL;
    ui_AIChatMenuRssi0 = NULL;

}
