// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIRecognitionScr = NULL;
lv_obj_t * ui_AIRecognitionPageIndexDot1 = NULL;
lv_obj_t * ui_AIRecognitionPageIndexDot2 = NULL;
lv_obj_t * ui_AIRecognitionPageIndexDot0 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_AIRecognitionCont = NULL;
lv_obj_t * ui_AIRecognitionLab = NULL;
lv_obj_t * ui_AIRecohnitionWiFiCont = NULL;
lv_obj_t * ui_AIRecognitionRssi5 = NULL;
lv_obj_t * ui_AIRecognitionRssi4 = NULL;
lv_obj_t * ui_AIRecognitionRssi3 = NULL;
lv_obj_t * ui_AIRecognitionRssi2 = NULL;
lv_obj_t * ui_AIRecognitionRssi1 = NULL;
lv_obj_t * ui_AIRecognitionRssi0 = NULL;
// event funtions
void ui_event_AIRecognitionScr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AIChatSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatSrc_screen_init);
    }

}

// void ui_event_ImgButton2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
//       if(current_wifi_connected)
//       {
//         //vTaskResume(activate_task_handle);
//         // device_active_check = true;
//         //_ui_screen_change(&ui_ServerConnectSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ServerConnectSrc_screen_init);
//         AIChat_Device_Bound_Check = 3;
//         vTaskResume(video_stream_task_handle);
//       }
//       else
//       {
//         _ui_screen_change(&ui_WiFiNoConnectSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WiFiNoConnectSrc_screen_init);
//       }
//     }
// }

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t * indev = lv_indev_get_act();

    static lv_point_t press_point;

    if(event_code == LV_EVENT_PRESSED)
    {
        // 记录按下坐标
        lv_indev_get_point(indev, &press_point);
    }
    else if(event_code == LV_EVENT_RELEASED)
    {
        lv_point_t release_point;
        lv_indev_get_point(indev, &release_point);

        int dx = release_point.x - press_point.x;
        int dy = release_point.y - press_point.y;

        /* ---------- 滑动过滤 ---------- */
        if(LV_ABS(dx) > SLIDE_THRESHOLD &&
           LV_ABS(dx) > LV_ABS(dy))
        {
            // 是滑动，吞掉这次点击
            return;
        }

        /* ---------- 以下是你原来的点击逻辑 ---------- */
        if(current_wifi_connected)
        {
            AIChat_Device_Bound_Check = 3;
            //vTaskResume(video_stream_task_handle);
        }
        else
        {
            screen_index = 0;
            _ui_screen_change(&ui_WiFiNoConnectSrc,
                              LV_SCR_LOAD_ANIM_FADE_ON,
                              0, 0,
                              &ui_WiFiNoConnectSrc_screen_init);
        }
    }
}

// build funtions

void ui_AIRecognitionScr_screen_init(void)
{
    ui_AIRecognitionScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIRecognitionScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognitionScr, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imgbtn_create(ui_AIRecognitionScr);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lv2_ai_photo_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lv2_ai_photo_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 160);
    lv_obj_set_height(ui_ImgButton2, 100);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);

    ui_AIRecognitionPageIndexDot1 = lv_btn_create(ui_AIRecognitionScr);
    lv_obj_set_width(ui_AIRecognitionPageIndexDot1, 8);
    lv_obj_set_height(ui_AIRecognitionPageIndexDot1, 8);
    lv_obj_set_x(ui_AIRecognitionPageIndexDot1, 0);
    lv_obj_set_y(ui_AIRecognitionPageIndexDot1, 100);
    lv_obj_set_align(ui_AIRecognitionPageIndexDot1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionPageIndexDot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionPageIndexDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionPageIndexDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionPageIndexDot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionPageIndexDot2 = lv_btn_create(ui_AIRecognitionScr);
    lv_obj_set_width(ui_AIRecognitionPageIndexDot2, 8);
    lv_obj_set_height(ui_AIRecognitionPageIndexDot2, 8);
    lv_obj_set_x(ui_AIRecognitionPageIndexDot2, 30);
    lv_obj_set_y(ui_AIRecognitionPageIndexDot2, 100);
    lv_obj_set_align(ui_AIRecognitionPageIndexDot2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionPageIndexDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionPageIndexDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionPageIndexDot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionPageIndexDot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionPageIndexDot0 = lv_btn_create(ui_AIRecognitionScr);
    lv_obj_set_width(ui_AIRecognitionPageIndexDot0, 8);
    lv_obj_set_height(ui_AIRecognitionPageIndexDot0, 8);
    lv_obj_set_x(ui_AIRecognitionPageIndexDot0, -30);
    lv_obj_set_y(ui_AIRecognitionPageIndexDot0, 100);
    lv_obj_set_align(ui_AIRecognitionPageIndexDot0, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionPageIndexDot0, lv_color_hex(0x07F734), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionPageIndexDot0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionPageIndexDot0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionPageIndexDot0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionCont = lv_obj_create(ui_AIRecognitionScr);
    lv_obj_remove_style_all(ui_AIRecognitionCont);
    lv_obj_set_width(ui_AIRecognitionCont, 240);
    lv_obj_set_height(ui_AIRecognitionCont, 50);
    lv_obj_set_x(ui_AIRecognitionCont, 0);
    lv_obj_set_y(ui_AIRecognitionCont, -117);
    lv_obj_set_align(ui_AIRecognitionCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecognitionCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AIRecognitionCont, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AIRecognitionCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionLab = lv_label_create(ui_AIRecognitionCont);
    lv_obj_set_height(ui_AIRecognitionLab, 20);
    lv_obj_set_width(ui_AIRecognitionLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_AIRecognitionLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIRecognitionLab, "AI Recognition");
    lv_obj_set_style_text_color(ui_AIRecognitionLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecognitionLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecognitionLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecohnitionWiFiCont = lv_obj_create(ui_AIRecognitionCont);
    lv_obj_remove_style_all(ui_AIRecohnitionWiFiCont);
    lv_obj_set_width(ui_AIRecohnitionWiFiCont, 20);
    lv_obj_set_height(ui_AIRecohnitionWiFiCont, 20);
    lv_obj_set_x(ui_AIRecohnitionWiFiCont, 85);
    lv_obj_set_y(ui_AIRecohnitionWiFiCont, 0);
    lv_obj_set_align(ui_AIRecohnitionWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecohnitionWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi5 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_AIRecognitionRssi5, 20);
    lv_obj_set_height(ui_AIRecognitionRssi5, 20);
    lv_obj_set_align(ui_AIRecognitionRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi4 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_AIRecognitionRssi4, 20);
    lv_obj_set_height(ui_AIRecognitionRssi4, 20);
    lv_obj_set_align(ui_AIRecognitionRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi3 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_AIRecognitionRssi3, 20);
    lv_obj_set_height(ui_AIRecognitionRssi3, 20);
    lv_obj_set_align(ui_AIRecognitionRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi2 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_AIRecognitionRssi2, 20);
    lv_obj_set_height(ui_AIRecognitionRssi2, 20);
    lv_obj_set_align(ui_AIRecognitionRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi1 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_AIRecognitionRssi1, 20);
    lv_obj_set_height(ui_AIRecognitionRssi1, 20);
    lv_obj_set_align(ui_AIRecognitionRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionRssi0 = lv_img_create(ui_AIRecohnitionWiFiCont);
    lv_img_set_src(ui_AIRecognitionRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_AIRecognitionRssi0, 20);
    lv_obj_set_height(ui_AIRecognitionRssi0, 20);
    lv_obj_set_align(ui_AIRecognitionRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionRssi0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIRecognitionScr, ui_event_AIRecognitionScr, LV_EVENT_ALL, NULL);

}

void ui_AIRecognitionScr_screen_destroy(void)
{
    if(ui_AIRecognitionScr) lv_obj_del(ui_AIRecognitionScr);

    // NULL screen variables
    ui_AIRecognitionScr = NULL;
    ui_ImgButton2 = NULL;
    ui_AIRecognitionPageIndexDot1 = NULL;
    ui_AIRecognitionPageIndexDot2 = NULL;
    ui_AIRecognitionPageIndexDot0 = NULL;
    ui_AIRecohnitionWiFiCont = NULL;
    ui_AIRecognitionCont = NULL;
    ui_AIRecognitionRssi5 = NULL;
    ui_AIRecognitionRssi4 = NULL;
    ui_AIRecognitionRssi3 = NULL;
    ui_AIRecognitionRssi2 = NULL;
    ui_AIRecognitionRssi1 = NULL;
    ui_AIRecognitionRssi0 = NULL;
    ui_AIRecognitionLab = NULL;

}
