// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AIRECOGNITION_H
#define UI_AIRECOGNITION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIRecognition
extern void ui_AIRecognition_screen_init(void);
extern void ui_AIRecognition_screen_destroy(void);
extern lv_obj_t * ui_AIRecognition;
extern lv_obj_t * ui_AIRecognitionDisplayImg;
extern lv_obj_t * ui_AIRecognitionTitleCont;
extern lv_obj_t * ui_AIRecognitionReturnImg;
extern lv_obj_t * ui_AIRecognitionTitleLab;
extern void ui_event_AIRecognitionReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_AIRecognitionReturnBtn;
extern lv_obj_t * ui_AIRecognitionLedOffImg;
extern lv_obj_t * ui_AIRecognitionLedOnImg;
extern void ui_event_AIRecognitionLedBtn(lv_event_t * e);
extern lv_obj_t * ui_AIRecognitionLedBtn;
extern lv_obj_t * ui_AIRecognitionIdentifyBtn;
extern lv_obj_t * ui_AIRecognitionSpinner;
extern lv_obj_t * ui_press_lab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

