// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AICHATMENU_H
#define UI_AICHATMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIChatMenu
extern void ui_AIChatMenu_screen_init(void);
extern void ui_AIChatMenu_screen_destroy(void);
extern lv_obj_t * ui_AIChatMenu;
extern lv_obj_t * ui_AIChatMenuTitleCont;
extern lv_obj_t * ui_AIChatMenuReturnImg;
extern lv_obj_t * ui_AIChatMenuTitleLab;
extern void ui_event_AIChatMenuReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_AIChatMenuReturnBtn;
extern lv_obj_t * ui_ELEServerCont;
extern lv_obj_t * ui_ELEServerContImg;
extern lv_obj_t * ui_ELEServerLab;
extern lv_obj_t * ui_ELEServerBtn;
extern lv_obj_t * ui_XiaozhiServerCont;
extern lv_obj_t * ui_XiaozhiServerLab;
extern lv_obj_t * ui_XiaozhiServerImg;
extern lv_obj_t * ui_XiaozhiServerBtn;
extern lv_obj_t * ui_AIChatMenuWiFiCont;
extern lv_obj_t * ui_AIChatMenuRssi5;
extern lv_obj_t * ui_AIChatMenuRssi4;
extern lv_obj_t * ui_AIChatMenuRssi3;
extern lv_obj_t * ui_AIChatMenuRssi2;
extern lv_obj_t * ui_AIChatMenuRssi1;
extern lv_obj_t * ui_AIChatMenuRssi0;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

