// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AICHATSRC_H
#define UI_AICHATSRC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIChatSrc
extern void ui_AIChatSrc_screen_init(void);
extern void ui_AIChatSrc_screen_destroy(void);
extern void ui_event_AIChatSrc(lv_event_t * e);
extern lv_obj_t * ui_AIChatSrc;
extern void ui_event_AIChatEntryImg(lv_event_t * e);
extern lv_obj_t * ui_AIChatEntryImg;
extern lv_obj_t * ui_AIChatPageIndexDot0;
extern lv_obj_t * ui_AIChatPageIndexDot1;
extern lv_obj_t * ui_AIChatPageIndexDot2;
extern lv_obj_t * ui_AIChatSrcTopCont;
extern lv_obj_t * ui_AIChatSrcWiFiCont;
extern lv_obj_t * ui_AIChatSrcWiFiRssi5;
extern lv_obj_t * ui_AIChatSrcWiFiRssi4;
extern lv_obj_t * ui_AIChatSrcWiFiRssi3;
extern lv_obj_t * ui_AIChatSrcWiFiRssi2;
extern lv_obj_t * ui_AIChatSrcWiFiRssi1;
extern lv_obj_t * ui_AIChatSrcWiFiRssi0;
extern lv_obj_t * ui_AIChatSrcLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

