// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AIRECOGNITIONSAVE_H
#define UI_AIRECOGNITIONSAVE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIRecognitionSave
extern void ui_AIRecognitionSave_screen_init(void);
extern void ui_AIRecognitionSave_screen_destroy(void);
extern lv_obj_t * ui_AIRecognitionSave;
extern lv_obj_t * ui_AIRecognitionSaveImg;
extern lv_obj_t * ui_AIRecognitionResultLab;
extern lv_obj_t * ui_AIRecognitionSaveSDLab;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_AIRecognitionSaveReturnBtn;
extern lv_obj_t * ui_AIRecognitionSaveeReturn;
extern lv_obj_t * ui_AIRecognitionSaveBtn;
extern lv_obj_t * ui_AIRecognitionSaveBtnImg;
extern lv_obj_t * ui_AIRecognitionSaveTitleLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

