
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIRecognition = NULL;
lv_obj_t * ui_AIRecognitionDisplayImg = NULL;
lv_obj_t * ui_AIRecognitionTitleCont = NULL;
lv_obj_t * ui_AIRecognitionReturnImg = NULL;
lv_obj_t * ui_AIRecognitionTitleLab = NULL;
lv_obj_t * ui_AIRecognitionReturnBtn = NULL;
lv_obj_t * ui_AIRecognitionLedOffImg = NULL;
lv_obj_t * ui_AIRecognitionLedOnImg = NULL;
lv_obj_t * ui_AIRecognitionLedBtn = NULL;
lv_obj_t * ui_AIRecognitionIdentifyBtn = NULL;
lv_obj_t * ui_AIRecognitionSpinner = NULL;
lv_obj_t * ui_press_lab = NULL;
// event funtions
void ui_event_AIRecognitionReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AIRecognitionScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionScr_screen_init);
        vTaskSuspend(video_stream_task_handle);
        current_fun_is_Recognition = false;
        aichat_exit = true;
    }
}

void ui_event_AIRecognitionLedBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        led_status = !led_status;
        if(led_status == true)
        {
            lv_obj_add_flag(ui_AIRecognitionLedOffImg, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_AIRecognitionLedOnImg, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            lv_obj_add_flag(ui_AIRecognitionLedOnImg, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(ui_AIRecognitionLedOffImg, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

void ui_event_AIRecognitionIdentifyBtn(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);

  if(event_code == LV_EVENT_CLICKED) {
    AI_Recognition_flag = true;

    //_ui_screen_change(&ui_AIRecognitionSave, LV_SCR_LOAD_ANIM_FADE_ON, 0, 2000, &ui_AIRecognitionSave_screen_init);
  }
}

// build funtions

void ui_AIRecognition_screen_init(void)
{
    ui_AIRecognition = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIRecognition, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognition, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognition, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionDisplayImg = lv_img_create(ui_AIRecognition);
    lv_obj_set_width(ui_AIRecognitionDisplayImg, 240);
    lv_obj_set_height(ui_AIRecognitionDisplayImg, 284);
    lv_obj_set_align(ui_AIRecognitionDisplayImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionDisplayImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionDisplayImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionTitleCont = lv_obj_create(ui_AIRecognition);
    lv_obj_remove_style_all(ui_AIRecognitionTitleCont);
    lv_obj_set_width(ui_AIRecognitionTitleCont, 240);
    lv_obj_set_height(ui_AIRecognitionTitleCont, 50);
    lv_obj_set_x(ui_AIRecognitionTitleCont, 0);
    lv_obj_set_y(ui_AIRecognitionTitleCont, -117);
    lv_obj_set_align(ui_AIRecognitionTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecognitionTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognitionTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionReturnImg = lv_img_create(ui_AIRecognitionTitleCont);
    lv_img_set_src(ui_AIRecognitionReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_AIRecognitionReturnImg, 20);
    lv_obj_set_height(ui_AIRecognitionReturnImg, 20);
    lv_obj_set_x(ui_AIRecognitionReturnImg, -85);
    lv_obj_set_y(ui_AIRecognitionReturnImg, 0);
    lv_obj_set_align(ui_AIRecognitionReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionTitleLab = lv_label_create(ui_AIRecognitionTitleCont);
    lv_obj_set_width(ui_AIRecognitionTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIRecognitionTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AIRecognitionTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIRecognitionTitleLab, "AI Recognition");
    lv_obj_set_style_text_color(ui_AIRecognitionTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecognitionTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecognitionTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionReturnBtn = lv_btn_create(ui_AIRecognitionTitleCont);
    lv_obj_set_width(ui_AIRecognitionReturnBtn, 100);
    lv_obj_set_height(ui_AIRecognitionReturnBtn, 50);
    lv_obj_set_x(ui_AIRecognitionReturnBtn, -70);
    lv_obj_set_y(ui_AIRecognitionReturnBtn, 0);
    lv_obj_set_align(ui_AIRecognitionReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionLedOffImg = lv_img_create(ui_AIRecognitionTitleCont);
    lv_img_set_src(ui_AIRecognitionLedOffImg, &ui_img_icon_fill_light_off_png);
    lv_obj_set_width(ui_AIRecognitionLedOffImg, 20);
    lv_obj_set_height(ui_AIRecognitionLedOffImg, 20);
    lv_obj_set_x(ui_AIRecognitionLedOffImg, 85);
    lv_obj_set_y(ui_AIRecognitionLedOffImg, 0);
    lv_obj_set_align(ui_AIRecognitionLedOffImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionLedOffImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionLedOffImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionLedOnImg = lv_img_create(ui_AIRecognitionTitleCont);
    lv_img_set_src(ui_AIRecognitionLedOnImg, &ui_img_icon_fill_light_on_png);
    lv_obj_set_width(ui_AIRecognitionLedOnImg, 20);
    lv_obj_set_height(ui_AIRecognitionLedOnImg, 20);
    lv_obj_set_x(ui_AIRecognitionLedOnImg, 85);
    lv_obj_set_y(ui_AIRecognitionLedOnImg, 0);
    lv_obj_set_align(ui_AIRecognitionLedOnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionLedOnImg, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionLedOnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionLedBtn = lv_btn_create(ui_AIRecognitionTitleCont);
    lv_obj_set_width(ui_AIRecognitionLedBtn, 100);
    lv_obj_set_height(ui_AIRecognitionLedBtn, 40);
    lv_obj_set_x(ui_AIRecognitionLedBtn, 70);
    lv_obj_set_y(ui_AIRecognitionLedBtn, 0);
    lv_obj_set_align(ui_AIRecognitionLedBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionLedBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionLedBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionLedBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionLedBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionIdentifyBtn = lv_imgbtn_create(ui_AIRecognition);
    lv_imgbtn_set_src(ui_AIRecognitionIdentifyBtn, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_icon_press_green_png, NULL);
    lv_imgbtn_set_src(ui_AIRecognitionIdentifyBtn, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_icon_press_green_png, NULL);
    lv_obj_set_width(ui_AIRecognitionIdentifyBtn, 30);
    lv_obj_set_height(ui_AIRecognitionIdentifyBtn, 30);
    lv_obj_set_x(ui_AIRecognitionIdentifyBtn, 0);
    lv_obj_set_y(ui_AIRecognitionIdentifyBtn, 100);
    lv_obj_set_align(ui_AIRecognitionIdentifyBtn, LV_ALIGN_CENTER);

    ui_AIRecognitionSpinner = lv_spinner_create(ui_AIRecognition, 1000, 90);
    lv_obj_set_width(ui_AIRecognitionSpinner, 48);
    lv_obj_set_height(ui_AIRecognitionSpinner, 48);
    lv_obj_set_x(ui_AIRecognitionSpinner, 3);
    lv_obj_set_y(ui_AIRecognitionSpinner, -2);
    lv_obj_set_align(ui_AIRecognitionSpinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionSpinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognitionSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AIRecognitionSpinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AIRecognitionSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_AIRecognitionSpinner, &ui_img_loading_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);


    ui_press_lab = lv_label_create(ui_AIRecognition);
    lv_obj_set_width(ui_press_lab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_press_lab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_press_lab, 0);
    lv_obj_set_y(ui_press_lab, 129);
    lv_obj_set_align(ui_press_lab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_press_lab, "Press");
    lv_obj_set_style_text_color(ui_press_lab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_press_lab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_press_lab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AIRecognitionReturnBtn, ui_event_AIRecognitionReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIRecognitionLedBtn, ui_event_AIRecognitionLedBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIRecognitionIdentifyBtn, ui_event_AIRecognitionIdentifyBtn, LV_EVENT_ALL, NULL);
}

void ui_AIRecognition_screen_destroy(void)
{
    if(ui_AIRecognition) lv_obj_del(ui_AIRecognition);

    // NULL screen variables
    ui_AIRecognition = NULL;
    ui_AIRecognitionDisplayImg = NULL;
    ui_AIRecognitionTitleCont = NULL;
    ui_AIRecognitionReturnImg = NULL;
    ui_AIRecognitionTitleLab = NULL;
    ui_AIRecognitionReturnBtn = NULL;
    ui_AIRecognitionLedOffImg = NULL;
    ui_AIRecognitionLedOnImg = NULL;
    ui_AIRecognitionLedBtn = NULL;
    ui_AIRecognitionIdentifyBtn = NULL;
    ui_AIRecognitionSpinner = NULL;
    ui_press_lab = NULL;

}
