// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIChatSrc = NULL;
lv_obj_t * ui_AIChatEntryImg = NULL;
lv_obj_t * ui_AIChatPageIndexDot0 = NULL;
lv_obj_t * ui_AIChatPageIndexDot1 = NULL;
lv_obj_t * ui_AIChatPageIndexDot2 = NULL;
lv_obj_t * ui_AIChatSrcTopCont = NULL;
lv_obj_t * ui_AIChatSrcWiFiCont = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi5 = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi4 = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi3 = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi2 = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi1 = NULL;
lv_obj_t * ui_AIChatSrcWiFiRssi0 = NULL;
lv_obj_t * ui_AIChatSrcLab = NULL;
// event funtions
void ui_event_AIChatSrc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_AIRecognitionScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionScr_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingScr_screen_init);
    }
}

// void ui_event_AIChatEntryImg(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);

//     if(event_code == LV_EVENT_CLICKED) {
        
//         if(current_wifi_connected)
//         {
//             _ui_screen_change(&ui_AIChatMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatMenu_screen_init);
//         }
//         else
//         {
//             _ui_screen_change(&ui_WiFiNoConnectSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WiFiNoConnectSrc_screen_init);
//         }
//     }
// }
#define SLIDE_THRESHOLD  20   // 与其它按钮保持统一

void ui_event_AIChatEntryImg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t * indev = lv_indev_get_act();

    static lv_point_t press_point;

    if(event_code == LV_EVENT_PRESSED)
    {
        // 记录按下坐标
        lv_indev_get_point(indev, &press_point);
    }
    else if(event_code == LV_EVENT_RELEASED)
    {
        lv_point_t release_point;
        lv_indev_get_point(indev, &release_point);

        int dx = release_point.x - press_point.x;
        int dy = release_point.y - press_point.y;

        /* ---------- 滑动过滤 ---------- */
        if(LV_ABS(dx) > SLIDE_THRESHOLD &&
           LV_ABS(dx) > LV_ABS(dy))
        {
            // 横向滑动，吞掉点击
            return;
        }

        /* ---------- 原来的点击逻辑 ---------- */
        if(current_wifi_connected)
        {
            _ui_screen_change(&ui_AIChatMenu,
                              LV_SCR_LOAD_ANIM_FADE_ON,
                              0, 300,
                              &ui_AIChatMenu_screen_init);
        }
        else
        {
            screen_index = 1;
            _ui_screen_change(&ui_WiFiNoConnectSrc,
                              LV_SCR_LOAD_ANIM_FADE_ON,
                              0, 0,
                              &ui_WiFiNoConnectSrc_screen_init);
        }
    }
}

// build funtions

void ui_AIChatSrc_screen_init(void)
{
    ui_AIChatSrc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIChatSrc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatSrc, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatSrc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatEntryImg = lv_imgbtn_create(ui_AIChatSrc);
    lv_imgbtn_set_src(ui_AIChatEntryImg, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_lv2_ai_dialogue_png, NULL);
    lv_imgbtn_set_src(ui_AIChatEntryImg, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_lv2_ai_dialogue_png, NULL);
    lv_obj_set_width(ui_AIChatEntryImg, 160);
    lv_obj_set_height(ui_AIChatEntryImg, 100);
    lv_obj_set_align(ui_AIChatEntryImg, LV_ALIGN_CENTER);

    ui_AIChatPageIndexDot0 = lv_btn_create(ui_AIChatSrc);
    lv_obj_set_width(ui_AIChatPageIndexDot0, 8);
    lv_obj_set_height(ui_AIChatPageIndexDot0, 8);
    lv_obj_set_x(ui_AIChatPageIndexDot0, -30);
    lv_obj_set_y(ui_AIChatPageIndexDot0, 100);
    lv_obj_set_align(ui_AIChatPageIndexDot0, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatPageIndexDot0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatPageIndexDot0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatPageIndexDot0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatPageIndexDot0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatPageIndexDot1 = lv_btn_create(ui_AIChatSrc);
    lv_obj_set_width(ui_AIChatPageIndexDot1, 8);
    lv_obj_set_height(ui_AIChatPageIndexDot1, 8);
    lv_obj_set_x(ui_AIChatPageIndexDot1, 0);
    lv_obj_set_y(ui_AIChatPageIndexDot1, 100);
    lv_obj_set_align(ui_AIChatPageIndexDot1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatPageIndexDot1, lv_color_hex(0x07F734), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatPageIndexDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatPageIndexDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatPageIndexDot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatPageIndexDot2 = lv_btn_create(ui_AIChatSrc);
    lv_obj_set_width(ui_AIChatPageIndexDot2, 8);
    lv_obj_set_height(ui_AIChatPageIndexDot2, 8);
    lv_obj_set_x(ui_AIChatPageIndexDot2, 30);
    lv_obj_set_y(ui_AIChatPageIndexDot2, 100);
    lv_obj_set_align(ui_AIChatPageIndexDot2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIChatPageIndexDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatPageIndexDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIChatPageIndexDot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIChatPageIndexDot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatSrcTopCont = lv_obj_create(ui_AIChatSrc);
    lv_obj_remove_style_all(ui_AIChatSrcTopCont);
    lv_obj_set_width(ui_AIChatSrcTopCont, 240);
    lv_obj_set_height(ui_AIChatSrcTopCont, 50);
    lv_obj_set_x(ui_AIChatSrcTopCont, 0);
    lv_obj_set_y(ui_AIChatSrcTopCont, -117);
    lv_obj_set_align(ui_AIChatSrcTopCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatSrcTopCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIChatSrcTopCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIChatSrcTopCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIChatSrcWiFiCont = lv_obj_create(ui_AIChatSrcTopCont);
    lv_obj_remove_style_all(ui_AIChatSrcWiFiCont);
    lv_obj_set_width(ui_AIChatSrcWiFiCont, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiCont, 20);
    lv_obj_set_x(ui_AIChatSrcWiFiCont, 85);
    lv_obj_set_y(ui_AIChatSrcWiFiCont, 0);
    lv_obj_set_align(ui_AIChatSrcWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIChatSrcWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi5 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi5, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi5, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi4 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi4, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi4, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi3 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi3, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi3, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi2 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi2, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi2, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi1 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi1, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi1, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcWiFiRssi0 = lv_img_create(ui_AIChatSrcWiFiCont);
    lv_img_set_src(ui_AIChatSrcWiFiRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_AIChatSrcWiFiRssi0, 20);
    lv_obj_set_height(ui_AIChatSrcWiFiRssi0, 20);
    lv_obj_set_align(ui_AIChatSrcWiFiRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIChatSrcWiFiRssi0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIChatSrcWiFiRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIChatSrcLab = lv_label_create(ui_AIChatSrcTopCont);
    lv_obj_set_height(ui_AIChatSrcLab, 20);
    lv_obj_set_width(ui_AIChatSrcLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_AIChatSrcLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIChatSrcLab, "AI Dialogue");
    lv_obj_set_style_text_color(ui_AIChatSrcLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIChatSrcLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIChatSrcLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AIChatEntryImg, ui_event_AIChatEntryImg, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIChatSrc, ui_event_AIChatSrc, LV_EVENT_ALL, NULL);

}

void ui_AIChatSrc_screen_destroy(void)
{
    if(ui_AIChatSrc) lv_obj_del(ui_AIChatSrc);

    // NULL screen variables
    ui_AIChatSrc = NULL;
    ui_AIChatEntryImg = NULL;
    ui_AIChatPageIndexDot0 = NULL;
    ui_AIChatPageIndexDot1 = NULL;
    ui_AIChatPageIndexDot2 = NULL;
    ui_AIChatSrcTopCont = NULL;
    ui_AIChatSrcWiFiCont = NULL;
    ui_AIChatSrcWiFiRssi5 = NULL;
    ui_AIChatSrcWiFiRssi4 = NULL;
    ui_AIChatSrcWiFiRssi3 = NULL;
    ui_AIChatSrcWiFiRssi2 = NULL;
    ui_AIChatSrcWiFiRssi1 = NULL;
    ui_AIChatSrcWiFiRssi0 = NULL;
    ui_AIChatSrcLab = NULL;

}
