// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AICHATEXITSCR_H
#define UI_AICHATEXITSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIChatExitScr
extern void ui_AIChatExitScr_screen_init(void);
extern void ui_AIChatExitScr_screen_destroy(void);
extern lv_obj_t * ui_AIChatExitScr;
extern lv_obj_t * ui_AIChatExitTitleCont;
extern lv_obj_t * ui_AIChatExitReturnImg;
extern lv_obj_t * ui_AIChatExitTitleLab;
extern lv_obj_t * ui_AIChatExitElEServerCont;
extern lv_obj_t * ui_AIChatExitELEImg;
extern lv_obj_t * ui_AIChatExitELELab;
extern lv_obj_t * ui_AIChatExitELEBtn;
extern lv_obj_t * ui_AIChatExitxzCont;
extern lv_obj_t * ui_AIChatExitxzLab;
extern lv_obj_t * ui_AIChatExitxzImg;
extern lv_obj_t * ui_AIChatExitxzBtn;
extern lv_obj_t * ui_AIChatExitWiFiCont;
extern lv_obj_t * ui_AIChatExitRssi;
extern lv_obj_t * ui_AIChatExitCont;
extern lv_obj_t * ui_AIChatExitSpinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
