#include "libraries/lvgl/src/core/lv_obj.h"
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIRecognitionSave = NULL;
lv_obj_t * ui_AIRecognitionSaveImg = NULL;
lv_obj_t * ui_AIRecognitionResultLab = NULL;
lv_obj_t * ui_AIRecognitionSaveSDLab = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_AIRecognitionSaveeReturn = NULL;
lv_obj_t * ui_AIRecognitionSaveBtn = NULL;
lv_obj_t * ui_AIRecognitionSaveBtnImg = NULL;
lv_obj_t * ui_AIRecognitionSaveTitleLab = NULL;
lv_obj_t * ui_AIRecognitionSaveReturnOpa = NULL;
lv_obj_t * ui_AIRecognitionSaveReturnImg = NULL;
lv_obj_t * ui_AIRecognitionSaveOpa = NULL;
// event funtions
void ui_event_AIRecognitionSaveReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        
        AI_Recognition_exit_flag = true;
    }
}

void ui_event_ui_AIRecognitionSaveBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
      img_save_to_sd_flag = true;
    }
}

// build funtions

void ui_AIRecognitionSave_screen_init(void)
{
    ui_AIRecognitionSave = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIRecognitionSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognitionSave, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveImg = lv_img_create(ui_AIRecognitionSave);
    lv_obj_set_width(ui_AIRecognitionSaveImg, 240);
    lv_obj_set_height(ui_AIRecognitionSaveImg, 284);
    lv_obj_set_align(ui_AIRecognitionSaveImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionSaveImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionSaveImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionResultLab = lv_label_create(ui_AIRecognitionSave);

    // 1. 设置固定宽度为 230
    lv_obj_set_width(ui_AIRecognitionResultLab, 210); 
    lv_obj_set_height(ui_AIRecognitionResultLab, LV_SIZE_CONTENT); 

    lv_label_set_long_mode(ui_AIRecognitionResultLab, LV_LABEL_LONG_WRAP);

    lv_obj_set_x(ui_AIRecognitionResultLab, 0);
    lv_obj_set_y(ui_AIRecognitionResultLab, 100);
    lv_obj_set_align(ui_AIRecognitionResultLab, LV_ALIGN_CENTER);
    
    lv_label_set_text(ui_AIRecognitionResultLab, "Result");

    lv_obj_set_style_text_color(ui_AIRecognitionResultLab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecognitionResultLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AIRecognitionResultLab, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionResultLab, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecognitionResultLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveSDLab = lv_label_create(ui_AIRecognitionSave);
    lv_obj_set_width(ui_AIRecognitionSaveSDLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIRecognitionSaveSDLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIRecognitionSaveSDLab, 0);
    lv_obj_set_y(ui_AIRecognitionSaveSDLab, -60);
    lv_obj_add_flag(ui_AIRecognitionSaveSDLab, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_AIRecognitionSaveSDLab, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_AIRecognitionSaveSDLab, lv_color_hex(0x00FFAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecognitionSaveSDLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AIRecognitionSaveSDLab, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSaveSDLab, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecognitionSaveSDLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_AIRecognitionSave);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 240);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_x(ui_Container7, 0);
    lv_obj_set_y(ui_Container7, -117);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveReturnOpa = lv_btn_create(ui_AIRecognitionSave);
    lv_obj_set_width(ui_AIRecognitionSaveReturnOpa, 40);
    lv_obj_set_height(ui_AIRecognitionSaveReturnOpa, 40);
    lv_obj_set_x(ui_AIRecognitionSaveReturnOpa, -86);
    lv_obj_set_y(ui_AIRecognitionSaveReturnOpa, -117);
    lv_obj_set_align(ui_AIRecognitionSaveReturnOpa, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecognitionSaveReturnOpa,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_AIRecognitionSaveReturnOpa, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AIRecognitionSaveReturnOpa, lv_color_hex(0x6B6666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSaveReturnOpa, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionSaveReturnOpa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionSaveReturnOpa, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveReturnImg = lv_img_create(ui_AIRecognitionSaveReturnOpa);
    lv_img_set_src(ui_AIRecognitionSaveReturnImg, &ui_img_icon_return_02_png);
    lv_obj_set_width(ui_AIRecognitionSaveReturnImg, 20);
    lv_obj_set_height(ui_AIRecognitionSaveReturnImg, 20);
    lv_obj_set_align(ui_AIRecognitionSaveReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionSaveReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionSaveReturnImg, LV_OBJ_FLAG_SCROLLABLE); 

    ui_AIRecognitionSaveOpa = lv_btn_create(ui_AIRecognitionSave);
    lv_obj_set_width(ui_AIRecognitionSaveOpa, 40);
    lv_obj_set_height(ui_AIRecognitionSaveOpa, 40);
    lv_obj_set_x(ui_AIRecognitionSaveOpa, 85);
    lv_obj_set_y(ui_AIRecognitionSaveOpa, -117);
    lv_obj_set_align(ui_AIRecognitionSaveOpa, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecognitionSaveOpa,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_AIRecognitionSaveOpa, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AIRecognitionSaveOpa, lv_color_hex(0x6B6666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSaveOpa, 175, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionSaveOpa, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionSaveOpa, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveBtnImg = lv_img_create(ui_AIRecognitionSaveOpa);
    lv_img_set_src(ui_AIRecognitionSaveBtnImg, &ui_img_icon_recognition_effect_01_png);
    lv_obj_set_width(ui_AIRecognitionSaveBtnImg, 20);
    lv_obj_set_height(ui_AIRecognitionSaveBtnImg, 20);
    lv_obj_set_align(ui_AIRecognitionSaveBtnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionSaveBtnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionSaveBtnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionSaveeReturn = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_AIRecognitionSaveeReturn, 100);
    lv_obj_set_height(ui_AIRecognitionSaveeReturn, 50);
    lv_obj_set_x(ui_AIRecognitionSaveeReturn, -70);
    lv_obj_set_y(ui_AIRecognitionSaveeReturn, 0);
    lv_obj_set_align(ui_AIRecognitionSaveeReturn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionSaveeReturn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSaveeReturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionSaveeReturn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionSaveeReturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveBtn = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_AIRecognitionSaveBtn, 100);
    lv_obj_set_height(ui_AIRecognitionSaveBtn, 47);
    lv_obj_set_x(ui_AIRecognitionSaveBtn, 68);
    lv_obj_set_y(ui_AIRecognitionSaveBtn, 0);
    lv_obj_set_align(ui_AIRecognitionSaveBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecognitionSaveBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionSaveBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecognitionSaveBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecognitionSaveBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecognitionSaveBtnImg = lv_img_create(ui_Container7);
    lv_img_set_src(ui_AIRecognitionSaveBtnImg, &ui_img_icon_recognition_effect_01_png);
    lv_obj_set_width(ui_AIRecognitionSaveBtnImg, 20);
    lv_obj_set_height(ui_AIRecognitionSaveBtnImg, 20);
    lv_obj_set_x(ui_AIRecognitionSaveBtnImg, 85);
    lv_obj_set_y(ui_AIRecognitionSaveBtnImg, 0);
    lv_obj_set_align(ui_AIRecognitionSaveBtnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecognitionSaveBtnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecognitionSaveBtnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecognitionSaveTitleLab = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_AIRecognitionSaveTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIRecognitionSaveTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AIRecognitionSaveTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIRecognitionSaveTitleLab, " ");
    lv_obj_set_style_text_color(ui_AIRecognitionSaveTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecognitionSaveTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecognitionSaveTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_AIRecognitionSaveeReturn, ui_event_AIRecognitionSaveReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AIRecognitionSaveBtn, ui_event_ui_AIRecognitionSaveBtn, LV_EVENT_ALL, NULL);
}

void ui_AIRecognitionSave_screen_destroy(void)
{
    if(ui_AIRecognitionSave) lv_obj_del(ui_AIRecognitionSave);

    // NULL screen variables
    ui_AIRecognitionSave = NULL;
    ui_AIRecognitionSaveImg = NULL;
    ui_AIRecognitionResultLab = NULL;
    ui_AIRecognitionSaveSDLab = NULL;
    ui_Container7 = NULL;
    ui_AIRecognitionSaveeReturn = NULL;
    ui_AIRecognitionSaveBtn = NULL;
    ui_AIRecognitionSaveBtnImg = NULL;
    ui_AIRecognitionSaveTitleLab = NULL;
    ui_AIRecognitionSaveReturnImg = NULL;

}
