// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_AIRecognitionExitScr = NULL;
lv_obj_t * ui_AIRecogExitPageIndexDot1 = NULL;
lv_obj_t * ui_AIRecogExitPageIndexDot2 = NULL;
lv_obj_t * ui_AIRecogExitPageIndexDot0 = NULL;
lv_obj_t * ui_AIRecogExitWiFiCont = NULL;
lv_obj_t * ui_AIRecogExitRssi = NULL;
lv_obj_t * ui_AIRecogExitLab = NULL;
lv_obj_t * ui_AIRecogExitImg = NULL;
lv_obj_t * ui_AIRecogExitCont = NULL;
lv_obj_t * ui_AIRecogExitSpinner = NULL;
// event funtions
static void async1_destroy_wrapper(void *param)
{
    (void)param; // 不使用参数
    ui_AIRecognitionExitScr_screen_destroy();
}

static void exit_screen_timer_cb(lv_timer_t *timer)
{
  if(current_active_screen == 3)
  {
      _ui_screen_change(&ui_AIRecognitionScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionScr_screen_init);
  }
    
    lv_timer_del(timer);
    lv_async_call(async1_destroy_wrapper, NULL);
}
// build funtions

void ui_AIRecognitionExitScr_screen_init(void)
{
    ui_AIRecognitionExitScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AIRecognitionExitScr,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_AIRecognitionExitScr, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecognitionExitScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitPageIndexDot1 = lv_btn_create(ui_AIRecognitionExitScr);
    lv_obj_set_width(ui_AIRecogExitPageIndexDot1, 8);
    lv_obj_set_height(ui_AIRecogExitPageIndexDot1, 8);
    lv_obj_set_x(ui_AIRecogExitPageIndexDot1, 0);
    lv_obj_set_y(ui_AIRecogExitPageIndexDot1, 100);
    lv_obj_set_align(ui_AIRecogExitPageIndexDot1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecogExitPageIndexDot1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecogExitPageIndexDot1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecogExitPageIndexDot1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecogExitPageIndexDot1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitPageIndexDot2 = lv_btn_create(ui_AIRecognitionExitScr);
    lv_obj_set_width(ui_AIRecogExitPageIndexDot2, 8);
    lv_obj_set_height(ui_AIRecogExitPageIndexDot2, 8);
    lv_obj_set_x(ui_AIRecogExitPageIndexDot2, 30);
    lv_obj_set_y(ui_AIRecogExitPageIndexDot2, 100);
    lv_obj_set_align(ui_AIRecogExitPageIndexDot2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecogExitPageIndexDot2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecogExitPageIndexDot2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecogExitPageIndexDot2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecogExitPageIndexDot2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitPageIndexDot0 = lv_btn_create(ui_AIRecognitionExitScr);
    lv_obj_set_width(ui_AIRecogExitPageIndexDot0, 8);
    lv_obj_set_height(ui_AIRecogExitPageIndexDot0, 8);
    lv_obj_set_x(ui_AIRecogExitPageIndexDot0, -30);
    lv_obj_set_y(ui_AIRecogExitPageIndexDot0, 100);
    lv_obj_set_align(ui_AIRecogExitPageIndexDot0, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_AIRecogExitPageIndexDot0, lv_color_hex(0x07F734), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecogExitPageIndexDot0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_AIRecogExitPageIndexDot0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AIRecogExitPageIndexDot0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitWiFiCont = lv_obj_create(ui_AIRecognitionExitScr);
    lv_obj_remove_style_all(ui_AIRecogExitWiFiCont);
    lv_obj_set_width(ui_AIRecogExitWiFiCont, 20);
    lv_obj_set_height(ui_AIRecogExitWiFiCont, 20);
    lv_obj_set_x(ui_AIRecogExitWiFiCont, 85);
    lv_obj_set_y(ui_AIRecogExitWiFiCont, -117);
    lv_obj_add_flag(ui_AIRecogExitWiFiCont, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_AIRecogExitWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecogExitWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecogExitRssi = lv_img_create(ui_AIRecogExitWiFiCont);
    lv_img_set_src(ui_AIRecogExitRssi, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_AIRecogExitRssi, 20);
    lv_obj_set_height(ui_AIRecogExitRssi, 20);
    lv_obj_set_align(ui_AIRecogExitRssi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecogExitRssi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_AIRecogExitRssi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AIRecogExitLab = lv_label_create(ui_AIRecognitionExitScr);
    lv_obj_set_height(ui_AIRecogExitLab, 20);
    lv_obj_set_width(ui_AIRecogExitLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_AIRecogExitLab, 0);
    lv_obj_set_y(ui_AIRecogExitLab, -117);
    lv_obj_set_align(ui_AIRecogExitLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AIRecogExitLab, "AI Recognition");
    lv_obj_set_style_text_color(ui_AIRecogExitLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AIRecogExitLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AIRecogExitLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitImg = lv_img_create(ui_AIRecognitionExitScr);
    lv_img_set_src(ui_AIRecogExitImg, &ui_img_lv2_ai_photo_png);
    lv_obj_set_width(ui_AIRecogExitImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AIRecogExitImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AIRecogExitImg, 0);
    lv_obj_set_y(ui_AIRecogExitImg, 0);
    lv_obj_set_align(ui_AIRecogExitImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AIRecogExitImg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_AIRecogExitImg,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_AIRecogExitCont = lv_obj_create(ui_AIRecognitionExitScr);
    lv_obj_remove_style_all(ui_AIRecogExitCont);
    lv_obj_set_width(ui_AIRecogExitCont, 240);
    lv_obj_set_height(ui_AIRecogExitCont, 284);
    lv_obj_set_align(ui_AIRecogExitCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecogExitCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecogExitCont, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecogExitCont, 125, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AIRecogExitSpinner = lv_spinner_create(ui_AIRecognitionExitScr, 1000, 90);
    lv_obj_set_width(ui_AIRecogExitSpinner, 48);
    lv_obj_set_height(ui_AIRecogExitSpinner, 48);
    lv_obj_set_x(ui_AIRecogExitSpinner, 3);
    lv_obj_set_y(ui_AIRecogExitSpinner, -2);
    lv_obj_set_align(ui_AIRecogExitSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AIRecogExitSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AIRecogExitSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AIRecogExitSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_AIRecogExitSpinner, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_AIRecogExitSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_img_src(ui_AIRecogExitSpinner, &ui_img_loading_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_timer_t *timer = lv_timer_create(exit_screen_timer_cb, 2500, NULL);

}

void ui_AIRecognitionExitScr_screen_destroy(void)
{
    if(ui_AIRecognitionExitScr) lv_obj_del(ui_AIRecognitionExitScr);

    // NULL screen variables
    ui_AIRecognitionExitScr = NULL;
    ui_AIRecogExitPageIndexDot1 = NULL;
    ui_AIRecogExitPageIndexDot2 = NULL;
    ui_AIRecogExitPageIndexDot0 = NULL;
    ui_AIRecogExitWiFiCont = NULL;
    ui_AIRecogExitRssi = NULL;
    ui_AIRecogExitLab = NULL;
    ui_AIRecogExitImg = NULL;
    ui_AIRecogExitCont = NULL;
    ui_AIRecogExitSpinner = NULL;

}
