// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_NETWORKCONFIGURE_H
#define UI_NETWORKCONFIGURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NetworkConfigure
extern void ui_NetworkConfigure_screen_init(void);
extern void ui_NetworkConfigure_screen_destroy(void);
extern lv_obj_t * ui_NetworkConfigure;
extern lv_obj_t * ui_NetworkConfigureTitleCont;
extern lv_obj_t * ui_NetworkConfigureReturnImg;
extern lv_obj_t * ui_NetworkConfigureTitleLab;
extern void ui_event_NetworkConfigureReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_NetworkConfigureReturnBtn;
extern lv_obj_t * ui_NetworkConfigureCont;
extern lv_obj_t * ui_NetworkConfigureLab;
extern lv_obj_t * ui_NetworkConfigureBtn;
extern lv_obj_t * ui_NetworkConfigureBtnLab;
extern lv_obj_t * ui_NetworkConfigureName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

