// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_RGBLight = NULL;
lv_obj_t * ui_RGBLightTitleCont = NULL;
lv_obj_t * ui_RGBLightReturnImg = NULL;
lv_obj_t * ui_RGBLightTitleLab = NULL;
lv_obj_t * ui_RGBLightReturnBtn = NULL;
lv_obj_t * ui_RGBLightFunctionCont = NULL;
lv_obj_t * ui_RGBLightSelectLab = NULL;
lv_obj_t * ui_RGBLightSelectOpenBtn = NULL;
lv_obj_t * ui_RGBLightSelectOpenLab = NULL;
lv_obj_t * ui_RGBLightCloseBtn = NULL;
lv_obj_t * ui_RGBLightCloseLab = NULL;
// event funtions
void ui_event_RGBLightReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
        ui_RGBLight_screen_destroy();
    }
}

void ui_event_rbglight_open(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e); 
    if(event_code == LV_EVENT_CLICKED){
        vTaskResume(RGB_Light_task_handle);
    } 
}

void ui_event_rbglight_close(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e); 
    if(event_code == LV_EVENT_CLICKED){
        vTaskSuspend(RGB_Light_task_handle);
        RGBLighCloseSem = true;
    } 
}

// build funtions

void ui_RGBLight_screen_init(void)
{
    ui_RGBLight = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RGBLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RGBLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightTitleCont = lv_obj_create(ui_RGBLight);
    lv_obj_remove_style_all(ui_RGBLightTitleCont);
    lv_obj_set_width(ui_RGBLightTitleCont, 240);
    lv_obj_set_height(ui_RGBLightTitleCont, 50);
    lv_obj_set_x(ui_RGBLightTitleCont, 0);
    lv_obj_set_y(ui_RGBLightTitleCont, -117);
    lv_obj_set_align(ui_RGBLightTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGBLightTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RGBLightTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightReturnImg = lv_img_create(ui_RGBLightTitleCont);
    lv_img_set_src(ui_RGBLightReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_RGBLightReturnImg, 20);
    lv_obj_set_height(ui_RGBLightReturnImg, 20);
    lv_obj_set_x(ui_RGBLightReturnImg, -85);
    lv_obj_set_y(ui_RGBLightReturnImg, 0);
    lv_obj_set_align(ui_RGBLightReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RGBLightReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RGBLightReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RGBLightTitleLab = lv_label_create(ui_RGBLightTitleCont);
    lv_obj_set_width(ui_RGBLightTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGBLightTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RGBLightTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RGBLightTitleLab, "RGB Light");
    lv_obj_set_style_text_color(ui_RGBLightTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RGBLightTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RGBLightTitleLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightReturnBtn = lv_btn_create(ui_RGBLightTitleCont);
    lv_obj_set_width(ui_RGBLightReturnBtn, 100);
    lv_obj_set_height(ui_RGBLightReturnBtn, 50);
    lv_obj_set_x(ui_RGBLightReturnBtn, -70);
    lv_obj_set_y(ui_RGBLightReturnBtn, 0);
    lv_obj_set_align(ui_RGBLightReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RGBLightReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RGBLightReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RGBLightReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightFunctionCont = lv_obj_create(ui_RGBLight);
    lv_obj_remove_style_all(ui_RGBLightFunctionCont);
    lv_obj_set_width(ui_RGBLightFunctionCont, 220);
    lv_obj_set_height(ui_RGBLightFunctionCont, 160);
    lv_obj_set_align(ui_RGBLightFunctionCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGBLightFunctionCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RGBLightFunctionCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightFunctionCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightSelectLab = lv_label_create(ui_RGBLightFunctionCont);
    lv_obj_set_width(ui_RGBLightSelectLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGBLightSelectLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RGBLightSelectLab, 0);
    lv_obj_set_y(ui_RGBLightSelectLab, -45);
    lv_obj_set_align(ui_RGBLightSelectLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RGBLightSelectLab, "RGB Light Control");
    lv_obj_set_style_text_color(ui_RGBLightSelectLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RGBLightSelectLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RGBLightSelectLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightSelectOpenBtn = lv_btn_create(ui_RGBLightFunctionCont);
    lv_obj_set_width(ui_RGBLightSelectOpenBtn, 160);
    lv_obj_set_height(ui_RGBLightSelectOpenBtn, 30);
    lv_obj_set_align(ui_RGBLightSelectOpenBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RGBLightSelectOpenBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGBLightSelectOpenBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightSelectOpenBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGBLightSelectOpenBtn, lv_color_hex(0x06F665), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_RGBLightSelectOpenBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_RGBLightSelectOpenLab = lv_label_create(ui_RGBLightSelectOpenBtn);
    lv_obj_set_width(ui_RGBLightSelectOpenLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGBLightSelectOpenLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RGBLightSelectOpenLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RGBLightSelectOpenLab, "OPEN");
    lv_obj_set_style_text_color(ui_RGBLightSelectOpenLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RGBLightSelectOpenLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RGBLightSelectOpenLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightCloseBtn = lv_btn_create(ui_RGBLightFunctionCont);
    lv_obj_set_width(ui_RGBLightCloseBtn, 160);
    lv_obj_set_height(ui_RGBLightCloseBtn, 30);
    lv_obj_set_x(ui_RGBLightCloseBtn, 0);
    lv_obj_set_y(ui_RGBLightCloseBtn, 40);
    lv_obj_set_align(ui_RGBLightCloseBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RGBLightCloseBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGBLightCloseBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGBLightCloseBtn, lv_color_hex(0x06F665), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_RGBLightCloseBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_RGBLightCloseLab = lv_label_create(ui_RGBLightCloseBtn);
    lv_obj_set_width(ui_RGBLightCloseLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGBLightCloseLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RGBLightCloseLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RGBLightCloseLab, "CLOSE");
    lv_obj_set_style_text_color(ui_RGBLightCloseLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RGBLightCloseLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RGBLightCloseLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RGBLightReturnBtn, ui_event_RGBLightReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RGBLightSelectOpenBtn, ui_event_rbglight_open, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RGBLightCloseBtn, ui_event_rbglight_close, LV_EVENT_ALL, NULL);

}

void ui_RGBLight_screen_destroy(void)
{
    if(ui_RGBLight) lv_obj_del(ui_RGBLight);

    // NULL screen variables
    ui_RGBLight = NULL;
    ui_RGBLightTitleCont = NULL;
    ui_RGBLightReturnImg = NULL;
    ui_RGBLightTitleLab = NULL;
    ui_RGBLightReturnBtn = NULL;
    ui_RGBLightFunctionCont = NULL;
    ui_RGBLightSelectLab = NULL;
    ui_RGBLightSelectOpenBtn = NULL;
    ui_RGBLightSelectOpenLab = NULL;
    ui_RGBLightCloseBtn = NULL;
    ui_RGBLightCloseLab = NULL;

}
