// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SETTINGSCR_H
#define UI_SETTINGSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScr
extern void ui_SettingScr_screen_init(void);
extern void ui_SettingScr_screen_destroy(void);
extern void ui_event_SettingScr(lv_event_t * e);
extern lv_obj_t * ui_SettingScr;
extern void ui_event_SettingEntryImg(lv_event_t * e);
extern lv_obj_t * ui_SettingEntryImg;
extern lv_obj_t * ui_SettingPageIndexDot1;
extern lv_obj_t * ui_SettingPageIndexDot0;
extern lv_obj_t * ui_SettingPageIndexDot2;
extern lv_obj_t * ui_SettingTopCont;
extern lv_obj_t * ui_SettingSrcWiFiCont;
extern lv_obj_t * ui_SettingSrcRssi5;
extern lv_obj_t * ui_SettingSrcRssi4;
extern lv_obj_t * ui_SettingSrcRssi3;
extern lv_obj_t * ui_SettingSrcRssi2;
extern lv_obj_t * ui_SettingSrcRssi1;
extern lv_obj_t * ui_SettingSrcRssi0;
extern lv_obj_t * ui_SettingSrcLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

