// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SDCARD_H
#define UI_SDCARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SDCard
extern void ui_SDCard_screen_init(void);
extern void ui_SDCard_screen_destroy(void);
extern lv_obj_t * ui_SDCard;
extern lv_obj_t * ui_SDCardTitleCont;
extern lv_obj_t * ui_SDCardReturnImg;
extern lv_obj_t * ui_SDCardTitleLab;
extern void ui_event_SDCardReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_SDCardReturnBtn;
extern lv_obj_t * ui_SDCardFunctionCont;
extern lv_obj_t * ui_SDCardImg2;
extern lv_obj_t * ui_SDCardLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

