// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ShotdownScr = NULL;
lv_obj_t * ui_PoweroffTitleCont = NULL;
lv_obj_t * ui_PoweroffReturnImg = NULL;
lv_obj_t * ui_PoweroffTitleLab = NULL;
lv_obj_t * ui_PoweroffReturnBtn = NULL;
lv_obj_t * ui_PoweroffSlider = NULL;
lv_obj_t * ui_PoweroffLab = NULL;
lv_obj_t * ui_PoweroffWiFiCont = NULL;
lv_obj_t * ui_PoweroffSrcRssi5 = NULL;
lv_obj_t * ui_PoweroffSrcRssi4 = NULL;
lv_obj_t * ui_PoweroffSrcRssi3 = NULL;
lv_obj_t * ui_PoweroffSrcRssi2 = NULL;
lv_obj_t * ui_PoweroffSrcRssi1 = NULL;
lv_obj_t * ui_PoweroffSrcRssi0 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Container1 = NULL;
// event funtions
void ui_event_PoweroffReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
    }
}

static void ui_event_PoweroffSlider(lv_event_t * e) {
    lv_obj_t * slider = lv_event_get_target(e);
    lv_event_code_t code = lv_event_get_code(e);

    if(code == LV_EVENT_RELEASED) {
        int v = lv_slider_get_value(slider);
        if(v > 80) {
            // 触发关机逻辑
            lv_slider_set_value(slider, 100, LV_ANIM_ON);
            Power_Off = true;
        } else {
            // 未滑到底，弹回初始位置
            lv_slider_set_value(slider, 0, LV_ANIM_ON);
        }
    }
}

// build funtions

void ui_ShotdownScr_screen_init(void)
{
    ui_ShotdownScr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ShotdownScr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ShotdownScr, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShotdownScr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweroffTitleCont = lv_obj_create(ui_ShotdownScr);
    lv_obj_remove_style_all(ui_PoweroffTitleCont);
    lv_obj_set_width(ui_PoweroffTitleCont, 240);
    lv_obj_set_height(ui_PoweroffTitleCont, 50);
    lv_obj_set_x(ui_PoweroffTitleCont, 0);
    lv_obj_set_y(ui_PoweroffTitleCont, -117);
    lv_obj_set_align(ui_PoweroffTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PoweroffTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PoweroffTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PoweroffTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweroffReturnImg = lv_img_create(ui_PoweroffTitleCont);
    lv_img_set_src(ui_PoweroffReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_PoweroffReturnImg, 20);
    lv_obj_set_height(ui_PoweroffReturnImg, 20);
    lv_obj_set_x(ui_PoweroffReturnImg, -85);
    lv_obj_set_y(ui_PoweroffReturnImg, 0);
    lv_obj_set_align(ui_PoweroffReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffTitleLab = lv_label_create(ui_PoweroffTitleCont);
    lv_obj_set_width(ui_PoweroffTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PoweroffTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PoweroffTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PoweroffTitleLab, "Power off");
    lv_obj_set_style_text_color(ui_PoweroffTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PoweroffTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PoweroffTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweroffReturnBtn = lv_btn_create(ui_PoweroffTitleCont);
    lv_obj_set_width(ui_PoweroffReturnBtn, 100);
    lv_obj_set_height(ui_PoweroffReturnBtn, 50);
    lv_obj_set_x(ui_PoweroffReturnBtn, -70);
    lv_obj_set_y(ui_PoweroffReturnBtn, 0);
    lv_obj_set_align(ui_PoweroffReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PoweroffReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PoweroffReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_PoweroffReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_PoweroffReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_ShotdownScr);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 220);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 13);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button6, 220);
    lv_obj_set_height(ui_Button6, 50);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweroffLab = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_PoweroffLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PoweroffLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PoweroffLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PoweroffLab, "slide to power off");
    lv_obj_set_style_text_color(ui_PoweroffLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PoweroffLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PoweroffLab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PoweroffSlider = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_PoweroffSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_PoweroffSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_PoweroffSlider, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_PoweroffSlider, 220);
    lv_obj_set_height(ui_PoweroffSlider, 50);
    lv_obj_set_align(ui_PoweroffSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_PoweroffSlider, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PoweroffSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PoweroffSlider, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PoweroffSlider, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PoweroffSlider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PoweroffSlider, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PoweroffSlider, lv_color_hex(0x292E33), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PoweroffSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_PoweroffSlider, &ui_img_icon_power_off_png, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PoweroffSlider, -4, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PoweroffSlider, -6, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PoweroffSlider, -5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PoweroffSlider, -5, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PoweroffWiFiCont = lv_obj_create(ui_PoweroffTitleCont);
    lv_obj_remove_style_all(ui_PoweroffWiFiCont);
    lv_obj_set_width(ui_PoweroffWiFiCont, 20);
    lv_obj_set_height(ui_PoweroffWiFiCont, 20);
    lv_obj_set_x(ui_PoweroffWiFiCont, 85);
    lv_obj_set_y(ui_PoweroffWiFiCont, 0);
    lv_obj_set_align(ui_PoweroffWiFiCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PoweroffWiFiCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi5 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_PoweroffSrcRssi5, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi5, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi4 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_PoweroffSrcRssi4, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi4, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi3 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_PoweroffSrcRssi3, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi3, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi2 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_PoweroffSrcRssi2, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi2, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi1 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_PoweroffSrcRssi1, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi1, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PoweroffSrcRssi0 = lv_img_create(ui_PoweroffWiFiCont);
    lv_img_set_src(ui_PoweroffSrcRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_PoweroffSrcRssi0, 20);
    lv_obj_set_height(ui_PoweroffSrcRssi0, 20);
    lv_obj_set_align(ui_PoweroffSrcRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PoweroffSrcRssi0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PoweroffSrcRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_PoweroffReturnBtn, ui_event_PoweroffReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PoweroffSlider, ui_event_PoweroffSlider, LV_EVENT_ALL, NULL);

}

void ui_ShotdownScr_screen_destroy(void)
{
    if(ui_ShotdownScr) lv_obj_del(ui_ShotdownScr);

    // NULL screen variables
    ui_ShotdownScr = NULL;
    ui_PoweroffTitleCont = NULL;
    ui_PoweroffReturnImg = NULL;
    ui_PoweroffTitleLab = NULL;
    ui_PoweroffReturnBtn = NULL;
    ui_PoweroffSlider = NULL;
    ui_PoweroffLab = NULL;
    ui_PoweroffSrcRssi0 = NULL;
    ui_PoweroffSrcRssi1 = NULL;
    ui_PoweroffSrcRssi2 = NULL;
    ui_PoweroffSrcRssi3 = NULL;
    ui_PoweroffSrcRssi4 = NULL;
    ui_PoweroffSrcRssi5 = NULL;
    ui_PoweroffWiFiCont = NULL;
    ui_Button6 = NULL;
    ui_Container1 = NULL;
}
