
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SDCard = NULL;
lv_obj_t * ui_SDCardTitleCont = NULL;
lv_obj_t * ui_SDCardReturnImg = NULL;
lv_obj_t * ui_SDCardTitleLab = NULL;
lv_obj_t * ui_SDCardReturnBtn = NULL;
lv_obj_t * ui_SDCardFunctionCont = NULL;
lv_obj_t * ui_SDCardImg2 = NULL;
lv_obj_t * ui_SDCardLab = NULL;
// event funtions
void ui_event_SDCardReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_label_set_text(ui_SDCardLab, "Waiting...");
        lv_obj_clear_flag(ui_SDCardReturnImg, LV_OBJ_FLAG_HIDDEN);
        lv_obj_clear_flag(ui_SDCardReturnBtn, LV_OBJ_FLAG_HIDDEN);
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
    }
}

void ui_event_SDCard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
       //xTaskNotifyGive(SD_Card_task_handle);
    }
}

// build funtions

void ui_SDCard_screen_init(void)
{
    ui_SDCard = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SDCard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SDCard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SDCard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardTitleCont = lv_obj_create(ui_SDCard);
    lv_obj_remove_style_all(ui_SDCardTitleCont);
    lv_obj_set_width(ui_SDCardTitleCont, 240);
    lv_obj_set_height(ui_SDCardTitleCont, 50);
    lv_obj_set_x(ui_SDCardTitleCont, 0);
    lv_obj_set_y(ui_SDCardTitleCont, -117);
    lv_obj_set_align(ui_SDCardTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SDCardTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SDCardTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SDCardTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardReturnImg = lv_img_create(ui_SDCardTitleCont);
    lv_img_set_src(ui_SDCardReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_SDCardReturnImg, 20);
    lv_obj_set_height(ui_SDCardReturnImg, 20);
    lv_obj_set_x(ui_SDCardReturnImg, -85);
    lv_obj_set_y(ui_SDCardReturnImg, 0);
    lv_obj_add_flag(ui_SDCardReturnImg, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_align(ui_SDCardReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDCardReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SDCardReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SDCardTitleLab = lv_label_create(ui_SDCardTitleCont);
    lv_obj_set_width(ui_SDCardTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDCardTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SDCardTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SDCardTitleLab, "SD Card");
    lv_obj_set_style_text_color(ui_SDCardTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SDCardTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SDCardTitleLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardReturnBtn = lv_btn_create(ui_SDCardTitleCont);
    lv_obj_set_width(ui_SDCardReturnBtn, 100);
    lv_obj_set_height(ui_SDCardReturnBtn, 50);
    lv_obj_set_x(ui_SDCardReturnBtn, -70);
    lv_obj_set_y(ui_SDCardReturnBtn, 0);
    lv_obj_set_align(ui_SDCardReturnBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDCardReturnBtn, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_SDCardReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SDCardReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SDCardReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SDCardReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardFunctionCont = lv_obj_create(ui_SDCard);
    lv_obj_remove_style_all(ui_SDCardFunctionCont);
    lv_obj_set_width(ui_SDCardFunctionCont, 220);
    lv_obj_set_height(ui_SDCardFunctionCont, 160);
    lv_obj_set_align(ui_SDCardFunctionCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SDCardFunctionCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SDCardFunctionCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SDCardFunctionCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardImg2 = lv_img_create(ui_SDCardFunctionCont);
    lv_img_set_src(ui_SDCardImg2, &ui_img_icon_sd_card_01_png);
    lv_obj_set_width(ui_SDCardImg2, 60);
    lv_obj_set_height(ui_SDCardImg2, 60);
    lv_obj_set_x(ui_SDCardImg2, 0);
    lv_obj_set_y(ui_SDCardImg2, -20);
    lv_obj_set_align(ui_SDCardImg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDCardImg2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SDCardImg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SDCardLab = lv_label_create(ui_SDCardFunctionCont);
    lv_obj_set_width(ui_SDCardLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDCardLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDCardLab, 0);
    lv_obj_set_y(ui_SDCardLab, 35);
    lv_obj_set_align(ui_SDCardLab, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_SDCardLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SDCardLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_SDCardLab, "Waiting...");
    lv_obj_set_style_text_font(ui_SDCardLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SDCardReturnBtn, ui_event_SDCardReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SDCard, ui_event_SDCard, LV_EVENT_ALL, NULL);


}

void ui_SDCard_screen_destroy(void)
{
    if(ui_SDCard) lv_obj_del(ui_SDCard);

    // NULL screen variables
    ui_SDCard = NULL;
    ui_SDCardTitleCont = NULL;
    ui_SDCardReturnImg = NULL;
    ui_SDCardTitleLab = NULL;
    ui_SDCardReturnBtn = NULL;
    ui_SDCardFunctionCont = NULL;
    ui_SDCardImg2 = NULL;
    ui_SDCardLab = NULL;

}
