// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SETTINGSRCMENU_H
#define UI_SETTINGSRCMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingSrcMenu
extern void ui_SettingSrcMenu_screen_init(void);
extern void ui_SettingSrcMenu_screen_destroy(void);
extern lv_obj_t * ui_SettingSrcMenu;
extern lv_obj_t * ui_SettingSrcMenuTitleCont;
extern lv_obj_t * ui_SettingSrcMenuReturnImg;
extern lv_obj_t * ui_SettingSrcMenuTitleLab;
extern void ui_event_SettingSrcReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_SettingSrcReturnBtn;
extern lv_obj_t * ui_SettingSrcMenuCont;
extern lv_obj_t * ui_ConfigNetworkBtn;
extern lv_obj_t * ui_ConfigNetworkLab;
extern lv_obj_t * ui_ConfigureNetworkImg;
extern lv_obj_t * ui_WiFiNetworkEntryBtn;
extern lv_obj_t * ui_WiFINetworkEntryLab;
extern lv_obj_t * ui_WiFiNetworkEntryImg;
extern lv_obj_t * ui_ScreenBrightnessBtn;
extern lv_obj_t * ui_ScreenBrightnessLab;
extern lv_obj_t * ui_ScreenBrightnessImg;
extern lv_obj_t * ui_RGBLightBtn;
extern lv_obj_t * ui_RGBLightLab;
extern lv_obj_t * ui_RGBLightImg;
extern lv_obj_t * ui_SDCardBtn;
extern lv_obj_t * ui_SDCardEntryLab;
extern lv_obj_t * ui_SDCardEntryImg;
extern lv_obj_t * ui_ResetToFactoryBtn;
extern lv_obj_t * ui_ResetToFactoryLab;
extern lv_obj_t * ui_ResetToFactoryImg;
extern lv_obj_t * ui_VersionBtn;
extern lv_obj_t * ui_VersionLab;
extern lv_obj_t * ui_SettingSrcWiFiCont2;
extern lv_obj_t * ui_SettingSrcMenuRssi5;
extern lv_obj_t * ui_SettingSrcMenuRssi4;
extern lv_obj_t * ui_SettingSrcMenuRssi3;
extern lv_obj_t * ui_SettingSrcMenuRssi2;
extern lv_obj_t * ui_SettingSrcMenuRssi1;
extern lv_obj_t * ui_SettingSrcMenuRssi0;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

