// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ScreenBrightness = NULL;
lv_obj_t * ui_BrightnessTitleCont = NULL;
lv_obj_t * ui_BrightnessReturnImg = NULL;
lv_obj_t * ui_BrightnessTitleLab = NULL;
lv_obj_t * ui_BrightnessReturnBtn = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_BrightnessSliderStripe1 = NULL;
lv_obj_t * ui_BrightnessSliderStripe2 = NULL;
lv_obj_t * ui_BrightnessSliderStripe3 = NULL;
lv_obj_t * ui_BrightnessSliderStripe4 = NULL;
lv_obj_t * ui_BrightnessSliderStripe5 = NULL;
lv_obj_t * ui_BrightnessSliderStripe6 = NULL;
lv_obj_t * ui_BrightnessSliderStripe7 = NULL;
lv_obj_t * ui_BrightnessSliderStripe8 = NULL;
lv_obj_t * ui_BrightnessSliderStripe9 = NULL;
lv_obj_t * ui_BrightnessADD = NULL;
lv_obj_t * ui_BrightnessReduce = NULL;
// event funtions
void ui_event_BrightnessReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
        ui_ScreenBrightness_screen_destroy();
    }
}

void ui_BrightnessSlider_event_cb(lv_event_t * e)
{
    lv_obj_t *slider = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(slider); 

    brightness_value = value;
}

// build funtions

void ui_ScreenBrightness_screen_init(void)
{
    ui_ScreenBrightness = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenBrightness, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessTitleCont = lv_obj_create(ui_ScreenBrightness);
    lv_obj_remove_style_all(ui_BrightnessTitleCont);
    lv_obj_set_width(ui_BrightnessTitleCont, 240);
    lv_obj_set_height(ui_BrightnessTitleCont, 50);
    lv_obj_set_x(ui_BrightnessTitleCont, 0);
    lv_obj_set_y(ui_BrightnessTitleCont, -117);
    lv_obj_set_align(ui_BrightnessTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BrightnessTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessReturnImg = lv_img_create(ui_BrightnessTitleCont);
    lv_img_set_src(ui_BrightnessReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_BrightnessReturnImg, 20);
    lv_obj_set_height(ui_BrightnessReturnImg, 20);
    lv_obj_set_x(ui_BrightnessReturnImg, -85);
    lv_obj_set_y(ui_BrightnessReturnImg, 0);
    lv_obj_set_align(ui_BrightnessReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessTitleLab = lv_label_create(ui_BrightnessTitleCont);
    lv_obj_set_width(ui_BrightnessTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessTitleLab, "Screen Brightness");
    lv_obj_set_style_text_color(ui_BrightnessTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BrightnessTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BrightnessTitleLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessReturnBtn = lv_btn_create(ui_BrightnessTitleCont);
    lv_obj_set_width(ui_BrightnessReturnBtn, 100);
    lv_obj_set_height(ui_BrightnessReturnBtn, 50);
    lv_obj_set_x(ui_BrightnessReturnBtn, -70);
    lv_obj_set_y(ui_BrightnessReturnBtn, 0);
    lv_obj_set_align(ui_BrightnessReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_ScreenBrightness);
    lv_slider_set_range(ui_BrightnessSlider, 1, 100);
    lv_slider_set_value(ui_BrightnessSlider, brightness_value, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 60);
    lv_obj_set_height(ui_BrightnessSlider, 127);
    lv_obj_set_x(ui_BrightnessSlider, 0);
    lv_obj_set_y(ui_BrightnessSlider, 15);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrightnessSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x17E67E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe1 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe1, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe1, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe1, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe1, 52);
    lv_obj_clear_flag(ui_BrightnessSliderStripe1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe2 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe2, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe2, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe2, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe2, 39);
    lv_obj_clear_flag(ui_BrightnessSliderStripe2, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe3 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe3, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe3, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe3, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe3, 26);
    lv_obj_clear_flag(ui_BrightnessSliderStripe3, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe3, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe4 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe4, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe4, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe4, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe4, 13);
    lv_obj_clear_flag(ui_BrightnessSliderStripe4, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe4, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe5 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe5, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe5, 3);
    lv_obj_set_align(ui_BrightnessSliderStripe5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessSliderStripe5, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe6 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe6, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe6, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe6, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe6, -13);
    lv_obj_clear_flag(ui_BrightnessSliderStripe6, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe6, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe7 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe7, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe7, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe7, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe7, -26);
    lv_obj_clear_flag(ui_BrightnessSliderStripe7, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe7, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe8 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe8, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe8, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe8, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe8, -39);
    lv_obj_clear_flag(ui_BrightnessSliderStripe8, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe8, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSliderStripe9 = lv_btn_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_BrightnessSliderStripe9, 60);
    lv_obj_set_height(ui_BrightnessSliderStripe9, 3);
    lv_obj_set_x(ui_BrightnessSliderStripe9, 0);
    lv_obj_set_y(ui_BrightnessSliderStripe9, -52);
    lv_obj_clear_flag(ui_BrightnessSliderStripe9, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_align(ui_BrightnessSliderStripe9, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BrightnessSliderStripe9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSliderStripe9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSliderStripe9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BrightnessSliderStripe9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BrightnessSliderStripe9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessADD = lv_img_create(ui_ScreenBrightness);
    lv_img_set_src(ui_BrightnessADD, &ui_img_brightness_plus_png);
    lv_obj_set_width(ui_BrightnessADD, 24);
    lv_obj_set_height(ui_BrightnessADD, 24);
    lv_obj_set_x(ui_BrightnessADD, 0);
    lv_obj_set_y(ui_BrightnessADD, -70);
    lv_obj_set_align(ui_BrightnessADD, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessADD, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessADD, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessReduce = lv_img_create(ui_ScreenBrightness);
    lv_img_set_src(ui_BrightnessReduce, &ui_img_brightness_reduce_png);
    lv_obj_set_width(ui_BrightnessReduce, 24);
    lv_obj_set_height(ui_BrightnessReduce, 24);
    lv_obj_set_x(ui_BrightnessReduce, 0);
    lv_obj_set_y(ui_BrightnessReduce, 100);
    lv_obj_set_align(ui_BrightnessReduce, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessReduce, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BrightnessReduce, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_obj_add_event_cb(ui_BrightnessReturnBtn, ui_event_BrightnessReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessSlider, ui_BrightnessSlider_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

}

void ui_ScreenBrightness_screen_destroy(void)
{
    if(ui_ScreenBrightness) lv_obj_del(ui_ScreenBrightness);

    // NULL screen variables
    ui_ScreenBrightness = NULL;
    ui_BrightnessTitleCont = NULL;
    ui_BrightnessReturnImg = NULL;
    ui_BrightnessTitleLab = NULL;
    ui_BrightnessReturnBtn = NULL;
    ui_BrightnessSlider = NULL;
    ui_BrightnessSliderStripe1 = NULL;
    ui_BrightnessSliderStripe2 = NULL;
    ui_BrightnessSliderStripe3 = NULL;
    ui_BrightnessSliderStripe4 = NULL;
    ui_BrightnessSliderStripe5 = NULL;
    ui_BrightnessSliderStripe6 = NULL;
    ui_BrightnessSliderStripe7 = NULL;
    ui_BrightnessSliderStripe8 = NULL;
    ui_BrightnessSliderStripe9 = NULL;
    ui_BrightnessADD = NULL;
    ui_BrightnessReduce = NULL;

}
