// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREENBRIGHTNESS_H
#define UI_SCREENBRIGHTNESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBrightness
extern void ui_ScreenBrightness_screen_init(void);
extern void ui_ScreenBrightness_screen_destroy(void);
extern lv_obj_t * ui_ScreenBrightness;
extern lv_obj_t * ui_BrightnessTitleCont;
extern lv_obj_t * ui_BrightnessReturnImg;
extern lv_obj_t * ui_BrightnessTitleLab;
extern void ui_event_BrightnessReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_BrightnessReturnBtn;
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_BrightnessSliderStripe1;
extern lv_obj_t * ui_BrightnessSliderStripe2;
extern lv_obj_t * ui_BrightnessSliderStripe3;
extern lv_obj_t * ui_BrightnessSliderStripe4;
extern lv_obj_t * ui_BrightnessSliderStripe5;
extern lv_obj_t * ui_BrightnessSliderStripe6;
extern lv_obj_t * ui_BrightnessSliderStripe7;
extern lv_obj_t * ui_BrightnessSliderStripe8;
extern lv_obj_t * ui_BrightnessSliderStripe9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

