// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SettingSrcMenu = NULL;
lv_obj_t * ui_SettingSrcMenuTitleCont = NULL;
lv_obj_t * ui_SettingSrcMenuReturnImg = NULL;
lv_obj_t * ui_SettingSrcMenuTitleLab = NULL;
lv_obj_t * ui_SettingSrcReturnBtn = NULL;
lv_obj_t * ui_SettingSrcMenuCont = NULL;
lv_obj_t * ui_ConfigNetworkBtn = NULL;
lv_obj_t * ui_ConfigNetworkLab = NULL;
lv_obj_t * ui_ConfigureNetworkImg = NULL;
lv_obj_t * ui_WiFiNetworkEntryBtn = NULL;
lv_obj_t * ui_WiFINetworkEntryLab = NULL;
lv_obj_t * ui_WiFiNetworkEntryImg = NULL;
lv_obj_t * ui_ScreenBrightnessBtn = NULL;
lv_obj_t * ui_ScreenBrightnessLab = NULL;
lv_obj_t * ui_ScreenBrightnessImg = NULL;
lv_obj_t * ui_RGBLightBtn = NULL;
lv_obj_t * ui_RGBLightLab = NULL;
lv_obj_t * ui_RGBLightImg = NULL;
lv_obj_t * ui_SDCardBtn = NULL;
lv_obj_t * ui_SDCardEntryLab = NULL;
lv_obj_t * ui_SDCardEntryImg = NULL;
lv_obj_t * ui_ResetToFactoryBtn = NULL;
lv_obj_t * ui_ResetToFactoryLab = NULL;
lv_obj_t * ui_ResetToFactoryImg = NULL;
lv_obj_t * ui_VersionBtn = NULL;
lv_obj_t * ui_VersionLab = NULL;
lv_obj_t * ui_SettingSrcWiFiCont2 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi5 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi4 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi3 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi2 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi1 = NULL;
lv_obj_t * ui_SettingSrcMenuRssi0 = NULL;
lv_obj_t * ui_ShutdownBtn = NULL;
lv_obj_t * ui_ShotdownLab = NULL;
lv_obj_t * ui_ShotdownImg = NULL;
// event funtions
void ui_event_SettingSrcReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingScr_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_ConfigNetworkBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_NetworkConfigure, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_NetworkConfigure_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_WiFiNetworkEntryBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFiNetwork, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WiFiNetwork_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_ScreenBrightnessBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenBrightness, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ScreenBrightness_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_RGBLightBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_RGBLight, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_RGBLight_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_SDCardBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        xTaskNotifyGive(SD_Card_task_handle);
        //_ui_screen_change(&ui_SDCard, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SDCard_screen_init);
    }
}

void ui_event_ResetToFactoryBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ResetToFactory, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ResetToFactory_screen_init);
        ui_SettingSrcMenu_screen_destroy();
    }
}

void ui_event_ShutdownBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ShotdownScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ShotdownScr_screen_init);
    }
}

// build funtions

void ui_SettingSrcMenu_screen_init(void)
{
    ui_SettingSrcMenu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingSrcMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingSrcMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSrcMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcMenuTitleCont = lv_obj_create(ui_SettingSrcMenu);
    lv_obj_remove_style_all(ui_SettingSrcMenuTitleCont);
    lv_obj_set_width(ui_SettingSrcMenuTitleCont, 240);
    lv_obj_set_height(ui_SettingSrcMenuTitleCont, 50);
    lv_obj_set_x(ui_SettingSrcMenuTitleCont, 0);
    lv_obj_set_y(ui_SettingSrcMenuTitleCont, -117);
    lv_obj_set_align(ui_SettingSrcMenuTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingSrcMenuTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingSrcMenuTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSrcMenuTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcMenuReturnImg = lv_img_create(ui_SettingSrcMenuTitleCont);
    lv_img_set_src(ui_SettingSrcMenuReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_SettingSrcMenuReturnImg, 20);
    lv_obj_set_height(ui_SettingSrcMenuReturnImg, 20);
    lv_obj_set_x(ui_SettingSrcMenuReturnImg, -85);
    lv_obj_set_y(ui_SettingSrcMenuReturnImg, 0);
    lv_obj_set_align(ui_SettingSrcMenuReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuTitleLab = lv_label_create(ui_SettingSrcMenuTitleCont);
    lv_obj_set_width(ui_SettingSrcMenuTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingSrcMenuTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingSrcMenuTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingSrcMenuTitleLab, "Setting");
    lv_obj_set_style_text_color(ui_SettingSrcMenuTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingSrcMenuTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingSrcMenuTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_SettingSrcReturnBtn = lv_btn_create(ui_SettingSrcMenuTitleCont);
    lv_obj_set_width(ui_SettingSrcReturnBtn, 100);
    lv_obj_set_height(ui_SettingSrcReturnBtn, 50);
    lv_obj_set_x(ui_SettingSrcReturnBtn, -70);
    lv_obj_set_y(ui_SettingSrcReturnBtn, 0);
    lv_obj_set_align(ui_SettingSrcReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_SettingSrcReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSrcReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SettingSrcReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SettingSrcReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcMenuCont = lv_obj_create(ui_SettingSrcMenu);
    lv_obj_remove_style_all(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_SettingSrcMenuCont, 220);
    lv_obj_set_height(ui_SettingSrcMenuCont, 224);
    lv_obj_set_x(ui_SettingSrcMenuCont, 0);
    lv_obj_set_y(ui_SettingSrcMenuCont, 25);
    lv_obj_set_align(ui_SettingSrcMenuCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingSrcMenuCont, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingSrcMenuCont, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingSrcMenuCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_ShutdownBtn, 220);
    lv_obj_set_height(ui_ShutdownBtn, 38);
    lv_obj_set_x(ui_ShutdownBtn, 0);
    lv_obj_set_y(ui_ShutdownBtn, -93);
    lv_obj_set_align(ui_ShutdownBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ShutdownBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ShutdownBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ShutdownBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ShutdownBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ShutdownBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShotdownLab = lv_label_create(ui_ShutdownBtn);
    lv_obj_set_width(ui_ShotdownLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShotdownLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShotdownLab, -63);
    lv_obj_set_y(ui_ShotdownLab, 0);
    lv_obj_set_align(ui_ShotdownLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShotdownLab, "Power off");
    lv_obj_set_style_text_font(ui_ShotdownLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShotdownImg = lv_img_create(ui_ShutdownBtn);
    lv_img_set_src(ui_ShotdownImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_ShotdownImg, 14);
    lv_obj_set_height(ui_ShotdownImg, 14);
    lv_obj_set_x(ui_ShotdownImg, 100);
    lv_obj_set_y(ui_ShotdownImg, 0);
    lv_obj_set_align(ui_ShotdownImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ShotdownImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ShotdownImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConfigNetworkBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_ConfigNetworkBtn, 220);
    lv_obj_set_height(ui_ConfigNetworkBtn, 38);
    lv_obj_set_x(ui_ConfigNetworkBtn, 0);
    lv_obj_set_y(ui_ConfigNetworkBtn, -53);
    lv_obj_set_align(ui_ConfigNetworkBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ConfigNetworkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfigNetworkBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigNetworkBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ConfigNetworkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ConfigNetworkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigNetworkLab = lv_label_create(ui_ConfigNetworkBtn);
    lv_obj_set_width(ui_ConfigNetworkLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfigNetworkLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfigNetworkLab, -30);
    lv_obj_set_y(ui_ConfigNetworkLab, 0);
    lv_obj_set_align(ui_ConfigNetworkLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfigNetworkLab, "Configure Network");
    lv_obj_set_style_text_font(ui_ConfigNetworkLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfigureNetworkImg = lv_img_create(ui_ConfigNetworkBtn);
    lv_img_set_src(ui_ConfigureNetworkImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_ConfigureNetworkImg, 14);
    lv_obj_set_height(ui_ConfigureNetworkImg, 14);
    lv_obj_set_x(ui_ConfigureNetworkImg, 100);
    lv_obj_set_y(ui_ConfigureNetworkImg, 0);
    lv_obj_set_align(ui_ConfigureNetworkImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfigureNetworkImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ConfigureNetworkImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiNetworkEntryBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_WiFiNetworkEntryBtn, 220);
    lv_obj_set_height(ui_WiFiNetworkEntryBtn, 38);
    lv_obj_set_x(ui_WiFiNetworkEntryBtn, 0);
    lv_obj_set_y(ui_WiFiNetworkEntryBtn, -13);
    lv_obj_set_align(ui_WiFiNetworkEntryBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_WiFiNetworkEntryBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiNetworkEntryBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNetworkEntryBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WiFiNetworkEntryBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WiFiNetworkEntryBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFINetworkEntryLab = lv_label_create(ui_WiFiNetworkEntryBtn);
    lv_obj_set_width(ui_WiFINetworkEntryLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFINetworkEntryLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFINetworkEntryLab, -50);
    lv_obj_set_y(ui_WiFINetworkEntryLab, 0);
    lv_obj_set_align(ui_WiFINetworkEntryLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFINetworkEntryLab, "WiFi Network");
    lv_obj_set_style_text_font(ui_WiFINetworkEntryLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNetworkEntryImg = lv_img_create(ui_WiFiNetworkEntryBtn);
    lv_img_set_src(ui_WiFiNetworkEntryImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_WiFiNetworkEntryImg, 14);
    lv_obj_set_height(ui_WiFiNetworkEntryImg, 14);
    lv_obj_set_x(ui_WiFiNetworkEntryImg, 100);
    lv_obj_set_y(ui_WiFiNetworkEntryImg, 0);
    lv_obj_set_align(ui_WiFiNetworkEntryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiNetworkEntryImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiNetworkEntryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenBrightnessBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_ScreenBrightnessBtn, 220);
    lv_obj_set_height(ui_ScreenBrightnessBtn, 38);
    lv_obj_set_x(ui_ScreenBrightnessBtn, 0);
    lv_obj_set_y(ui_ScreenBrightnessBtn, 27);
    lv_obj_set_align(ui_ScreenBrightnessBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ScreenBrightnessBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ScreenBrightnessBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenBrightnessBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ScreenBrightnessBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ScreenBrightnessBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenBrightnessLab = lv_label_create(ui_ScreenBrightnessBtn);
    lv_obj_set_width(ui_ScreenBrightnessLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScreenBrightnessLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScreenBrightnessLab, -32);
    lv_obj_set_y(ui_ScreenBrightnessLab, 0);
    lv_obj_set_align(ui_ScreenBrightnessLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScreenBrightnessLab, "Screen Brightness");
    lv_obj_set_style_text_font(ui_ScreenBrightnessLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScreenBrightnessImg = lv_img_create(ui_ScreenBrightnessBtn);
    lv_img_set_src(ui_ScreenBrightnessImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_ScreenBrightnessImg, 14);
    lv_obj_set_height(ui_ScreenBrightnessImg, 14);
    lv_obj_set_x(ui_ScreenBrightnessImg, 100);
    lv_obj_set_y(ui_ScreenBrightnessImg, 0);
    lv_obj_set_align(ui_ScreenBrightnessImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ScreenBrightnessImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ScreenBrightnessImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RGBLightBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_RGBLightBtn, 220);
    lv_obj_set_height(ui_RGBLightBtn, 38);
    lv_obj_set_x(ui_RGBLightBtn, 0);
    lv_obj_set_y(ui_RGBLightBtn, 67);
    lv_obj_set_align(ui_RGBLightBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RGBLightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RGBLightBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RGBLightBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RGBLightBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RGBLightBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightLab = lv_label_create(ui_RGBLightBtn);
    lv_obj_set_width(ui_RGBLightLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGBLightLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RGBLightLab, -61);
    lv_obj_set_y(ui_RGBLightLab, 0);
    lv_obj_set_align(ui_RGBLightLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RGBLightLab, "RGB Light");
    lv_obj_set_style_text_font(ui_RGBLightLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBLightImg = lv_img_create(ui_RGBLightBtn);
    lv_img_set_src(ui_RGBLightImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_RGBLightImg, 14);
    lv_obj_set_height(ui_RGBLightImg, 14);
    lv_obj_set_x(ui_RGBLightImg, 100);
    lv_obj_set_y(ui_RGBLightImg, 0);
    lv_obj_set_align(ui_RGBLightImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RGBLightImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RGBLightImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SDCardBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_SDCardBtn, 220);
    lv_obj_set_height(ui_SDCardBtn, 38);
    lv_obj_set_x(ui_SDCardBtn, 0);
    lv_obj_set_y(ui_SDCardBtn, 107);
    lv_obj_set_align(ui_SDCardBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SDCardBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SDCardBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SDCardBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_SDCardBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_SDCardBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardEntryLab = lv_label_create(ui_SDCardBtn);
    lv_obj_set_width(ui_SDCardEntryLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SDCardEntryLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SDCardEntryLab, -67);
    lv_obj_set_y(ui_SDCardEntryLab, 0);
    lv_obj_set_align(ui_SDCardEntryLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SDCardEntryLab, "SD Card");
    lv_obj_set_style_text_font(ui_SDCardEntryLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SDCardEntryImg = lv_img_create(ui_SDCardBtn);
    lv_img_set_src(ui_SDCardEntryImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_SDCardEntryImg, 14);
    lv_obj_set_height(ui_SDCardEntryImg, 14);
    lv_obj_set_x(ui_SDCardEntryImg, 100);
    lv_obj_set_y(ui_SDCardEntryImg, 0);
    lv_obj_set_align(ui_SDCardEntryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SDCardEntryImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SDCardEntryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResetToFactoryBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_ResetToFactoryBtn, 220);
    lv_obj_set_height(ui_ResetToFactoryBtn, 38);
    lv_obj_set_x(ui_ResetToFactoryBtn, 0);
    lv_obj_set_y(ui_ResetToFactoryBtn, 147);
    lv_obj_set_align(ui_ResetToFactoryBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ResetToFactoryBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetToFactoryBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactoryBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetToFactoryBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetToFactoryBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryLab = lv_label_create(ui_ResetToFactoryBtn);
    lv_obj_set_width(ui_ResetToFactoryLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetToFactoryLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetToFactoryLab, -8);
    lv_obj_set_y(ui_ResetToFactoryLab, 0);
    lv_obj_set_align(ui_ResetToFactoryLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetToFactoryLab, "Reset to Factory settings");
    lv_obj_set_style_text_font(ui_ResetToFactoryLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryImg = lv_img_create(ui_ResetToFactoryBtn);
    lv_img_set_src(ui_ResetToFactoryImg, &ui_img_set_next_step_01_png);
    lv_obj_set_width(ui_ResetToFactoryImg, 14);
    lv_obj_set_height(ui_ResetToFactoryImg, 14);
    lv_obj_set_x(ui_ResetToFactoryImg, 100);
    lv_obj_set_y(ui_ResetToFactoryImg, 0);
    lv_obj_set_align(ui_ResetToFactoryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetToFactoryImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ResetToFactoryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VersionBtn = lv_btn_create(ui_SettingSrcMenuCont);
    lv_obj_set_width(ui_VersionBtn, 220);
    lv_obj_set_height(ui_VersionBtn, 38);
    lv_obj_set_x(ui_VersionBtn, 0);
    lv_obj_set_y(ui_VersionBtn, 187);
    lv_obj_set_align(ui_VersionBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_VersionBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VersionBtn, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VersionBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VersionBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VersionBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLab = lv_label_create(ui_VersionBtn);
    lv_obj_set_width(ui_VersionLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLab, -59);
    lv_obj_set_y(ui_VersionLab, 0);
    lv_obj_set_align(ui_VersionLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionLab, "Version 1.0");
    lv_obj_set_style_text_font(ui_VersionLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingSrcWiFiCont2 = lv_obj_create(ui_SettingSrcMenu);
    lv_obj_remove_style_all(ui_SettingSrcWiFiCont2);
    lv_obj_set_width(ui_SettingSrcWiFiCont2, 20);
    lv_obj_set_height(ui_SettingSrcWiFiCont2, 20);
    lv_obj_set_x(ui_SettingSrcWiFiCont2, 85);
    lv_obj_set_y(ui_SettingSrcWiFiCont2, -117);
    lv_obj_set_align(ui_SettingSrcWiFiCont2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingSrcWiFiCont2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi5 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi5, &ui_img_icon_wifi_link_01_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi5, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi5, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi4 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi4, &ui_img_icon_wifi_link_02_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi4, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi4, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi3 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi3, &ui_img_icon_wifi_link_03_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi3, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi3, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi2 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi2, &ui_img_icon_wifi_link_04_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi2, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi2, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi1 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi1, &ui_img_icon_wifi_link_05_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi1, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi1, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingSrcMenuRssi0 = lv_img_create(ui_SettingSrcWiFiCont2);
    lv_img_set_src(ui_SettingSrcMenuRssi0, &ui_img_icon_wifi_no_link_01_png);
    lv_obj_set_width(ui_SettingSrcMenuRssi0, 20);
    lv_obj_set_height(ui_SettingSrcMenuRssi0, 20);
    lv_obj_set_align(ui_SettingSrcMenuRssi0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingSrcMenuRssi0, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingSrcMenuRssi0, LV_OBJ_FLAG_SCROLLABLE);      /// Flas

    lv_obj_add_event_cb(ui_ShutdownBtn, ui_event_ShutdownBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingSrcReturnBtn, ui_event_SettingSrcReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConfigNetworkBtn, ui_event_ConfigNetworkBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFiNetworkEntryBtn, ui_event_WiFiNetworkEntryBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScreenBrightnessBtn, ui_event_ScreenBrightnessBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RGBLightBtn, ui_event_RGBLightBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SDCardBtn, ui_event_SDCardBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetToFactoryBtn, ui_event_ResetToFactoryBtn, LV_EVENT_ALL, NULL);


}

void ui_SettingSrcMenu_screen_destroy(void)
{
    if(ui_SettingSrcMenu) lv_obj_del(ui_SettingSrcMenu);

    // NULL screen variables
    ui_SettingSrcMenu = NULL;
    ui_SettingSrcMenuTitleCont = NULL;
    ui_SettingSrcMenuReturnImg = NULL;
    ui_SettingSrcMenuTitleLab = NULL;
    ui_SettingSrcReturnBtn = NULL;
    ui_SettingSrcMenuCont = NULL;
    ui_ConfigNetworkBtn = NULL;
    ui_ConfigNetworkLab = NULL;
    ui_ConfigureNetworkImg = NULL;
    ui_WiFiNetworkEntryBtn = NULL;
    ui_WiFINetworkEntryLab = NULL;
    ui_WiFiNetworkEntryImg = NULL;
    ui_ScreenBrightnessBtn = NULL;
    ui_ScreenBrightnessLab = NULL;
    ui_ScreenBrightnessImg = NULL;
    ui_RGBLightBtn = NULL;
    ui_RGBLightLab = NULL;
    ui_RGBLightImg = NULL;
    ui_SDCardBtn = NULL;
    ui_SDCardEntryLab = NULL;
    ui_SDCardEntryImg = NULL;
    ui_ResetToFactoryBtn = NULL;
    ui_ResetToFactoryLab = NULL;
    ui_ResetToFactoryImg = NULL;
    ui_VersionBtn = NULL;
    ui_VersionLab = NULL;
    ui_SettingSrcWiFiCont2 = NULL;
    ui_SettingSrcMenuRssi5 = NULL;
    ui_SettingSrcMenuRssi4 = NULL;
    ui_SettingSrcMenuRssi3 = NULL;
    ui_SettingSrcMenuRssi2 = NULL;
    ui_SettingSrcMenuRssi1 = NULL;
    ui_SettingSrcMenuRssi0 = NULL;

}
