// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_WiFiNoConnectSrc = NULL;
lv_obj_t * ui_WiFINoConnetCont2 = NULL;
lv_obj_t * ui_WiFiNoConnectLab = NULL;
lv_obj_t * ui_WiFiNoConnectBtn = NULL;
lv_obj_t * ui_WiFiNoConnectBtnLab = NULL;
lv_obj_t * ui_WiFiNoConnectName = NULL;
// event funtions
void ui_event_WiFiNoConnectBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
      if(screen_index == 0)
      {
        _ui_screen_change(&ui_AIRecognitionScr, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIRecognitionScr_screen_init);
      }
      else
      {
        _ui_screen_change(&ui_AIChatSrc, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChatSrc_screen_init);
      }
       
    }
}
// build funtions

void ui_WiFiNoConnectSrc_screen_init(void)
{
    ui_WiFiNoConnectSrc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiNoConnectSrc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFiNoConnectSrc, lv_color_hex(0x142433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNoConnectSrc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFINoConnetCont2 = lv_obj_create(ui_WiFiNoConnectSrc);
    lv_obj_remove_style_all(ui_WiFINoConnetCont2);
    lv_obj_set_width(ui_WiFINoConnetCont2, 220);
    lv_obj_set_height(ui_WiFINoConnetCont2, 220);
    lv_obj_set_align(ui_WiFINoConnetCont2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WiFINoConnetCont2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WiFINoConnetCont2, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFINoConnetCont2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNoConnectLab = lv_label_create(ui_WiFINoConnetCont2);
    lv_obj_set_width(ui_WiFiNoConnectLab, 210);   /// 1
    lv_obj_set_height(ui_WiFiNoConnectLab, 220);    /// 1
    lv_obj_set_x(ui_WiFiNoConnectLab, 0);
    lv_obj_set_y(ui_WiFiNoConnectLab, 10);
    lv_obj_set_align(ui_WiFiNoConnectLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNoConnectLab,
                      "Connect your phone to the Wi-Fi hotspot:\n\n\nIf the webpage does not open automatically,\nplease visit http://192.168.4.1\.");
    lv_obj_set_style_text_color(ui_WiFiNoConnectLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiNoConnectLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiNoConnectLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNoConnectName = lv_label_create(ui_WiFINoConnetCont2);
    lv_obj_set_width(ui_WiFiNoConnectName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNoConnectName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiNoConnectName, 0);
    lv_obj_set_y(ui_WiFiNoConnectName, -51);
    lv_obj_set_align(ui_WiFiNoConnectName, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_WiFiNoConnectName, "%s", ssidstr_c);
    lv_obj_set_style_text_color(ui_WiFiNoConnectName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiNoConnectName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiNoConnectName, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_WiFiNoConnectBtn = lv_btn_create(ui_WiFINoConnetCont2);
    lv_obj_set_width(ui_WiFiNoConnectBtn, 160);
    lv_obj_set_height(ui_WiFiNoConnectBtn, 30);
    lv_obj_set_x(ui_WiFiNoConnectBtn, 0);
    lv_obj_set_y(ui_WiFiNoConnectBtn, 65);
    lv_obj_set_align(ui_WiFiNoConnectBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_WiFiNoConnectBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiNoConnectBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiNoConnectBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WiFiNoConnectBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WiFiNoConnectBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiNoConnectBtnLab = lv_label_create(ui_WiFiNoConnectBtn);
    lv_obj_set_width(ui_WiFiNoConnectBtnLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiNoConnectBtnLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WiFiNoConnectBtnLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiNoConnectBtnLab, "Cancel");
    lv_obj_set_style_text_font(ui_WiFiNoConnectBtnLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WiFiNoConnectBtn, ui_event_WiFiNoConnectBtn, LV_EVENT_ALL, NULL);
}

void ui_WiFiNoConnectSrc_screen_destroy(void)
{
    if(ui_WiFiNoConnectSrc) lv_obj_del(ui_WiFiNoConnectSrc);

    // NULL screen variables
    ui_WiFiNoConnectSrc = NULL;
    ui_WiFINoConnetCont2 = NULL;
    ui_WiFiNoConnectLab = NULL;
    ui_WiFiNoConnectBtn = NULL;
    ui_WiFiNoConnectBtnLab = NULL;
    ui_WiFiNoConnectName = NULL;

}
