// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_AIRECOGNITIONEXITSCR_H
#define UI_AIRECOGNITIONEXITSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AIRecognitionExitScr
extern void ui_AIRecognitionExitScr_screen_init(void);
extern void ui_AIRecognitionExitScr_screen_destroy(void);
extern void ui_event_AIRecognitionExitScr(lv_event_t * e);
extern lv_obj_t * ui_AIRecognitionExitScr;
extern lv_obj_t * ui_AIRecogExitPageIndexDot1;
extern lv_obj_t * ui_AIRecogExitPageIndexDot2;
extern lv_obj_t * ui_AIRecogExitPageIndexDot0;
extern lv_obj_t * ui_AIRecogExitWiFiCont;
extern lv_obj_t * ui_AIRecogExitRssi;
extern lv_obj_t * ui_AIRecogExitLab;
extern lv_obj_t * ui_AIRecogExitImg;
extern lv_obj_t * ui_AIRecogExitCont;
extern lv_obj_t * ui_AIRecogExitSpinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

