// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_ResetToFactory = NULL;
lv_obj_t * ui_ResetToFactoryTitleCont = NULL;
lv_obj_t * ui_ResetToFactoryReturnImg = NULL;
lv_obj_t * ui_ResetToFactoryTitleLab = NULL;
lv_obj_t * ui_ResetToFactoryReturnBtn = NULL;
lv_obj_t * ui_ResetToFactoryCont = NULL;
lv_obj_t * ui_ResetToFactorySelectLab = NULL;
lv_obj_t * ui_ResetToFactorySelectOKBtn = NULL;
lv_obj_t * ui_ResetToFactorySelectOKLab = NULL;
lv_obj_t * ui_ResetToFactorySelectCancelBtn = NULL;
lv_obj_t * ui_ResetToFactorySelectCancelLab = NULL;
// event funtions
void ui_event_ResetToFactoryReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingSrcMenu, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SettingSrcMenu_screen_init);
        ui_ResetToFactory_screen_destroy();
    }
}



void ui_event_ResetToFactoryOKBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
       reset_to_factory = true;
    }
}
// build funtions

void ui_ResetToFactory_screen_init(void)
{
    ui_ResetToFactory = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ResetToFactory, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetToFactory, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryTitleCont = lv_obj_create(ui_ResetToFactory);
    lv_obj_remove_style_all(ui_ResetToFactoryTitleCont);
    lv_obj_set_width(ui_ResetToFactoryTitleCont, 240);
    lv_obj_set_height(ui_ResetToFactoryTitleCont, 50);
    lv_obj_set_x(ui_ResetToFactoryTitleCont, 0);
    lv_obj_set_y(ui_ResetToFactoryTitleCont, -117);
    lv_obj_set_align(ui_ResetToFactoryTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ResetToFactoryTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetToFactoryTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactoryTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryReturnImg = lv_img_create(ui_ResetToFactoryTitleCont);
    lv_img_set_src(ui_ResetToFactoryReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_ResetToFactoryReturnImg, 20);
    lv_obj_set_height(ui_ResetToFactoryReturnImg, 20);
    lv_obj_set_x(ui_ResetToFactoryReturnImg, -85);
    lv_obj_set_y(ui_ResetToFactoryReturnImg, 0);
    lv_obj_set_align(ui_ResetToFactoryReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetToFactoryReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ResetToFactoryReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ResetToFactoryTitleLab = lv_label_create(ui_ResetToFactoryTitleCont);
    lv_obj_set_width(ui_ResetToFactoryTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetToFactoryTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetToFactoryTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetToFactoryTitleLab, "Reset to Factory Settigs");
    lv_obj_set_style_text_color(ui_ResetToFactoryTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetToFactoryTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetToFactoryTitleLab, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryReturnBtn = lv_btn_create(ui_ResetToFactoryTitleCont);
    lv_obj_set_width(ui_ResetToFactoryReturnBtn, 100);
    lv_obj_set_height(ui_ResetToFactoryReturnBtn, 50);
    lv_obj_set_x(ui_ResetToFactoryReturnBtn, -70);
    lv_obj_set_y(ui_ResetToFactoryReturnBtn, 0);
    lv_obj_set_align(ui_ResetToFactoryReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ResetToFactoryReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactoryReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ResetToFactoryReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ResetToFactoryReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactoryCont = lv_obj_create(ui_ResetToFactory);
    lv_obj_remove_style_all(ui_ResetToFactoryCont);
    lv_obj_set_width(ui_ResetToFactoryCont, 220);
    lv_obj_set_height(ui_ResetToFactoryCont, 160);
    lv_obj_set_align(ui_ResetToFactoryCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ResetToFactoryCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ResetToFactoryCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactoryCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactorySelectLab = lv_label_create(ui_ResetToFactoryCont);
    lv_obj_set_width(ui_ResetToFactorySelectLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetToFactorySelectLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ResetToFactorySelectLab, 0);
    lv_obj_set_y(ui_ResetToFactorySelectLab, -45);
    lv_obj_set_align(ui_ResetToFactorySelectLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetToFactorySelectLab, "Setting will be reset to\n             default?");
    lv_obj_set_style_text_color(ui_ResetToFactorySelectLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetToFactorySelectLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetToFactorySelectLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactorySelectOKBtn = lv_btn_create(ui_ResetToFactoryCont);
    lv_obj_set_width(ui_ResetToFactorySelectOKBtn, 160);
    lv_obj_set_height(ui_ResetToFactorySelectOKBtn, 30);
    lv_obj_set_align(ui_ResetToFactorySelectOKBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ResetToFactorySelectOKBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetToFactorySelectOKBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactorySelectOKBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetToFactorySelectOKBtn, lv_color_hex(0x06F665), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ResetToFactorySelectOKBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ResetToFactorySelectOKLab = lv_label_create(ui_ResetToFactorySelectOKBtn);
    lv_obj_set_width(ui_ResetToFactorySelectOKLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetToFactorySelectOKLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetToFactorySelectOKLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetToFactorySelectOKLab, "OK");
    lv_obj_set_style_text_color(ui_ResetToFactorySelectOKLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetToFactorySelectOKLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetToFactorySelectOKLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ResetToFactorySelectCancelBtn = lv_btn_create(ui_ResetToFactoryCont);
    lv_obj_set_width(ui_ResetToFactorySelectCancelBtn, 160);
    lv_obj_set_height(ui_ResetToFactorySelectCancelBtn, 30);
    lv_obj_set_x(ui_ResetToFactorySelectCancelBtn, 0);
    lv_obj_set_y(ui_ResetToFactorySelectCancelBtn, 40);
    lv_obj_set_align(ui_ResetToFactorySelectCancelBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ResetToFactorySelectCancelBtn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetToFactorySelectCancelBtn, lv_color_hex(0x667380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetToFactorySelectCancelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetToFactorySelectCancelBtn, lv_color_hex(0x06F665), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ResetToFactorySelectCancelBtn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ResetToFactorySelectCancelLab = lv_label_create(ui_ResetToFactorySelectCancelBtn);
    lv_obj_set_width(ui_ResetToFactorySelectCancelLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ResetToFactorySelectCancelLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ResetToFactorySelectCancelLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ResetToFactorySelectCancelLab, "Cancel");
    lv_obj_set_style_text_color(ui_ResetToFactorySelectCancelLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ResetToFactorySelectCancelLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ResetToFactorySelectCancelLab, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ResetToFactorySelectOKBtn, ui_event_ResetToFactoryOKBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetToFactoryReturnBtn, ui_event_ResetToFactoryReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ResetToFactorySelectCancelBtn, ui_event_ResetToFactoryReturnBtn, LV_EVENT_ALL, NULL);
}

void ui_ResetToFactory_screen_destroy(void)
{
    if(ui_ResetToFactory) lv_obj_del(ui_ResetToFactory);

    // NULL screen variables
    ui_ResetToFactory = NULL;
    ui_ResetToFactoryTitleCont = NULL;
    ui_ResetToFactoryReturnImg = NULL;
    ui_ResetToFactoryTitleLab = NULL;
    ui_ResetToFactoryReturnBtn = NULL;
    ui_ResetToFactoryCont = NULL;
    ui_ResetToFactorySelectLab = NULL;
    ui_ResetToFactorySelectOKBtn = NULL;
    ui_ResetToFactorySelectOKLab = NULL;
    ui_ResetToFactorySelectCancelBtn = NULL;
    ui_ResetToFactorySelectCancelLab = NULL;

}
