// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_RESETTOFACTORY_H
#define UI_RESETTOFACTORY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ResetToFactory
extern void ui_ResetToFactory_screen_init(void);
extern void ui_ResetToFactory_screen_destroy(void);
extern lv_obj_t * ui_ResetToFactory;
extern lv_obj_t * ui_ResetToFactoryTitleCont;
extern lv_obj_t * ui_ResetToFactoryReturnImg;
extern lv_obj_t * ui_ResetToFactoryTitleLab;
extern void ui_event_ResetToFactoryReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_ResetToFactoryReturnBtn;
extern lv_obj_t * ui_ResetToFactoryCont;
extern lv_obj_t * ui_ResetToFactorySelectLab;
extern lv_obj_t * ui_ResetToFactorySelectOKBtn;
extern lv_obj_t * ui_ResetToFactorySelectOKLab;
extern lv_obj_t * ui_ResetToFactorySelectCancelBtn;
extern lv_obj_t * ui_ResetToFactorySelectCancelLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

