// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SPLASHSCR_H
#define UI_SPLASHSCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SplashScr
extern void ui_SplashScr_screen_init(void);
extern void ui_SplashScr_screen_destroy(void);
extern void ui_event_SplashScr(lv_timer_t * timer);
extern lv_obj_t * ui_SplashScr;
extern lv_obj_t * ui_SplashScrImg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

