// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_ServerConnectSrc_screen_init(void);
extern void ui_ServerConnectSrc_screen_destroy(void);
extern lv_obj_t * ui_ServerConnectSrc;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ServerConnectBtn;
extern lv_obj_t * ui_WiFiNoConnectBtnLab2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ServerConnectSpinner;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

