// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_VolumSrc = NULL;
lv_obj_t * ui_VolumSrcTitleCont = NULL;
lv_obj_t * ui_VolumSrcTitleReturnImg = NULL;
lv_obj_t * ui_VolumSrcTitleLab = NULL;
lv_obj_t * ui_VolumSrcTitleReturnBtn = NULL;
lv_obj_t * ui_SliderCont = NULL;
lv_obj_t * ui_SpeakerSlider = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Button10 = NULL;
lv_obj_t * ui_Button11 = NULL;
lv_obj_t * ui_Button12 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_speakerLab = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Button13 = NULL;
lv_obj_t * ui_Button14 = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button18 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Button16 = NULL;
lv_obj_t * ui_Button19 = NULL;
lv_obj_t * ui_speakerLabOkBtn = NULL;
lv_obj_t * ui_speakerLabOkLab = NULL;
// event funtions
void ui_event_VolumSrcTitleReturnBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AIChat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AIChat_screen_init);
    }
}

void ui_event_speaker(lv_event_t *e) {
    lv_obj_t *slider = lv_event_get_target(e);
    int32_t value = lv_slider_get_value(slider); 
    
    speaker_value = value;
    lv_label_set_text_fmt(ui_speakerLab, "%d%%", speaker_value);
}

// build funtions

void ui_VolumSrc_screen_init(void)
{
    ui_VolumSrc = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_VolumSrc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VolumSrc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumSrc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumSrcTitleCont = lv_obj_create(ui_VolumSrc);
    lv_obj_remove_style_all(ui_VolumSrcTitleCont);
    lv_obj_set_width(ui_VolumSrcTitleCont, 240);
    lv_obj_set_height(ui_VolumSrcTitleCont, 50);
    lv_obj_set_x(ui_VolumSrcTitleCont, 0);
    lv_obj_set_y(ui_VolumSrcTitleCont, -117);
    lv_obj_set_align(ui_VolumSrcTitleCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VolumSrcTitleCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_VolumSrcTitleCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumSrcTitleCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumSrcTitleReturnImg = lv_img_create(ui_VolumSrcTitleCont);
    lv_img_set_src(ui_VolumSrcTitleReturnImg, &ui_img_icon_return_01_png);
    lv_obj_set_width(ui_VolumSrcTitleReturnImg, 20);
    lv_obj_set_height(ui_VolumSrcTitleReturnImg, 20);
    lv_obj_set_x(ui_VolumSrcTitleReturnImg, -85);
    lv_obj_set_y(ui_VolumSrcTitleReturnImg, 0);
    lv_obj_set_align(ui_VolumSrcTitleReturnImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VolumSrcTitleReturnImg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VolumSrcTitleReturnImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_VolumSrcTitleLab = lv_label_create(ui_VolumSrcTitleCont);
    lv_obj_set_width(ui_VolumSrcTitleLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumSrcTitleLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VolumSrcTitleLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VolumSrcTitleLab, "Speaker");
    lv_obj_set_style_text_color(ui_VolumSrcTitleLab, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VolumSrcTitleLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VolumSrcTitleLab, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumSrcTitleReturnBtn = lv_btn_create(ui_VolumSrcTitleCont);
    lv_obj_set_width(ui_VolumSrcTitleReturnBtn, 100);
    lv_obj_set_height(ui_VolumSrcTitleReturnBtn, 50);
    lv_obj_set_x(ui_VolumSrcTitleReturnBtn, -70);
    lv_obj_set_y(ui_VolumSrcTitleReturnBtn, 0);
    lv_obj_set_align(ui_VolumSrcTitleReturnBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_VolumSrcTitleReturnBtn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumSrcTitleReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_VolumSrcTitleReturnBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_VolumSrcTitleReturnBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderCont = lv_obj_create(ui_VolumSrc);
    lv_obj_remove_style_all(ui_SliderCont);
    lv_obj_set_width(ui_SliderCont, 220);
    lv_obj_set_height(ui_SliderCont, 160);
    lv_obj_set_align(ui_SliderCont, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SliderCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SliderCont, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderCont, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeakerSlider = lv_slider_create(ui_SliderCont);
    lv_slider_set_value(ui_SpeakerSlider, speaker_value, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SpeakerSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SpeakerSlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SpeakerSlider, 120);
    lv_obj_set_height(ui_SpeakerSlider, 20);
    lv_obj_set_x(ui_SpeakerSlider, 0);
    lv_obj_set_y(ui_SpeakerSlider, -15);
    lv_obj_set_align(ui_SpeakerSlider, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SpeakerSlider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeakerSlider, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeakerSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SpeakerSlider, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SpeakerSlider, lv_color_hex(0x17E67E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeakerSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SpeakerSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SpeakerSlider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SpeakerSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button2, 1);
    lv_obj_set_height(ui_Button2, 15);
    lv_obj_set_x(ui_Button2, -35);
    lv_obj_set_y(ui_Button2, -15);
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button4, 1);
    lv_obj_set_height(ui_Button4, 15);
    lv_obj_set_x(ui_Button4, -23);
    lv_obj_set_y(ui_Button4, -15);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button5, 1);
    lv_obj_set_height(ui_Button5, 15);
    lv_obj_set_x(ui_Button5, -11);
    lv_obj_set_y(ui_Button5, -15);
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button8, 1);
    lv_obj_set_height(ui_Button8, 15);
    lv_obj_set_x(ui_Button8, 0);
    lv_obj_set_y(ui_Button8, -15);
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button9 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button9, 1);
    lv_obj_set_height(ui_Button9, 15);
    lv_obj_set_x(ui_Button9, 11);
    lv_obj_set_y(ui_Button9, -15);
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button10 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button10, 1);
    lv_obj_set_height(ui_Button10, 15);
    lv_obj_set_x(ui_Button10, 23);
    lv_obj_set_y(ui_Button10, -15);
    lv_obj_clear_flag(ui_Button10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button10, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button10, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button11 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button11, 1);
    lv_obj_set_height(ui_Button11, 15);
    lv_obj_set_x(ui_Button11, 35);
    lv_obj_set_y(ui_Button11, -15);
    lv_obj_clear_flag(ui_Button11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button11, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button11, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button12 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button12, 1);
    lv_obj_set_height(ui_Button12, 15);
    lv_obj_set_x(ui_Button12, 47);
    lv_obj_set_y(ui_Button12, -15);
    lv_obj_clear_flag(ui_Button12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button12, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button12, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_SliderCont);
    lv_obj_set_width(ui_Button7, 1);
    lv_obj_set_height(ui_Button7, 15);
    lv_obj_set_x(ui_Button7, -47);
    lv_obj_set_y(ui_Button7, -15);
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE); 
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speakerLab = lv_label_create(ui_SliderCont);
    lv_obj_set_width(ui_speakerLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speakerLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speakerLab, 0);
    lv_obj_set_y(ui_speakerLab, -52);
    lv_obj_set_align(ui_speakerLab, LV_ALIGN_CENTER);
    lv_label_set_text_fmt(ui_speakerLab, "%d%%", speaker_value);
    lv_obj_set_style_text_color(ui_speakerLab, lv_color_hex(0x17E67E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speakerLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speakerLab, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_Container10 = lv_obj_create(ui_VolumSrc);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 20);
    lv_obj_set_height(ui_Container10, 20);
    lv_obj_set_x(ui_Container10, -87);
    lv_obj_set_y(ui_Container10, -15);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button13 = lv_btn_create(ui_Container10);
    lv_obj_set_width(ui_Button13, 20);
    lv_obj_set_height(ui_Button13, 20);
    lv_obj_set_align(ui_Button13, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button13, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button13, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button14 = lv_btn_create(ui_Container10);
    lv_obj_set_width(ui_Button14, 16);
    lv_obj_set_height(ui_Button14, 16);
    lv_obj_set_align(ui_Button14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button14, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button14, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button14, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button15 = lv_btn_create(ui_Container10);
    lv_obj_set_width(ui_Button15, 12);
    lv_obj_set_height(ui_Button15, 2);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_VolumSrc);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 20);
    lv_obj_set_height(ui_Container2, 20);
    lv_obj_set_x(ui_Container2, 87);
    lv_obj_set_y(ui_Container2, -15);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button18 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button18, 20);
    lv_obj_set_height(ui_Button18, 20);
    lv_obj_set_align(ui_Button18, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button18, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button18, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button1, 16);
    lv_obj_set_height(ui_Button1, 16);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x292E33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button16 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button16, 12);
    lv_obj_set_height(ui_Button16, 2);
    lv_obj_set_align(ui_Button16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button19 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button19, 2);
    lv_obj_set_height(ui_Button19, 12);
    lv_obj_set_align(ui_Button19, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Button19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_bg_color(ui_Button19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button19, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speakerLabOkBtn = lv_btn_create(ui_VolumSrc);
    lv_obj_set_width(ui_speakerLabOkBtn, 80);
    lv_obj_set_height(ui_speakerLabOkBtn, 30);
    lv_obj_set_x(ui_speakerLabOkBtn, 0);
    lv_obj_set_y(ui_speakerLabOkBtn, 40);
    lv_obj_set_align(ui_speakerLabOkBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_speakerLabOkBtn, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_speakerLabOkBtn, lv_color_hex(0x29CC7A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_speakerLabOkBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_speakerLabOkBtn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_speakerLabOkBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speakerLabOkLab = lv_label_create(ui_speakerLabOkBtn);
    lv_obj_set_width(ui_speakerLabOkLab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speakerLabOkLab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_speakerLabOkLab, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speakerLabOkLab, "OK");
    lv_obj_set_style_text_color(ui_speakerLabOkLab, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speakerLabOkLab, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speakerLabOkLab, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_VolumSrcTitleReturnBtn, ui_event_VolumSrcTitleReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_speakerLabOkBtn, ui_event_VolumSrcTitleReturnBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpeakerSlider, ui_event_speaker, LV_EVENT_VALUE_CHANGED, NULL);

} 

void ui_VolumSrc_screen_destroy(void)
{
    if(ui_VolumSrc) lv_obj_del(ui_VolumSrc);

    // NULL screen variables
    ui_VolumSrc = NULL;
    ui_VolumSrcTitleCont = NULL;
    ui_VolumSrcTitleReturnImg = NULL;
    ui_VolumSrcTitleLab = NULL;
    ui_VolumSrcTitleReturnBtn = NULL;
    ui_SliderCont = NULL;
    ui_SpeakerSlider = NULL;
    ui_Button2 = NULL;
    ui_Button4 = NULL;
    ui_Button5 = NULL;
    ui_Button8 = NULL;
    ui_Button9 = NULL;
    ui_Button10 = NULL;
    ui_Button11 = NULL;
    ui_Button12 = NULL;
    ui_Button7 = NULL;
    ui_speakerLab = NULL;
    ui_Container10 = NULL;
    ui_Button13 = NULL;
    ui_Button14 = NULL;
    ui_Button15 = NULL;
    ui_Container2 = NULL;
    ui_Button18 = NULL;
    ui_Button1 = NULL;
    ui_Button16 = NULL;
    ui_Button19 = NULL;
    ui_speakerLabOkBtn = NULL;
    ui_speakerLabOkLab = NULL;

}
