// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_VOLUMSRC_H
#define UI_VOLUMSRC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_VolumSrc
extern void ui_VolumSrc_screen_init(void);
extern void ui_VolumSrc_screen_destroy(void);
extern lv_obj_t * ui_VolumSrc;
extern lv_obj_t * ui_VolumSrcTitleCont;
extern lv_obj_t * ui_VolumSrcTitleReturnImg;
extern lv_obj_t * ui_VolumSrcTitleLab;
extern void ui_event_VolumSrcTitleReturnBtn(lv_event_t * e);
extern lv_obj_t * ui_VolumSrcTitleReturnBtn;
extern lv_obj_t * ui_SliderCont;
extern lv_obj_t * ui_SpeakerSlider;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_speakerLab;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_speakerLabOkBtn;
extern lv_obj_t * ui_speakerLabOkLab;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

