// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_WiFiNoConnectSrc_screen_init(void);
extern void ui_WiFiNoConnectSrc_screen_destroy(void);
extern lv_obj_t * ui_WiFiNoConnectSrc;
extern lv_obj_t * ui_WiFINoConnetCont2;
extern lv_obj_t * ui_WiFiNoConnectLab;
extern lv_obj_t * ui_WiFiNoConnectBtn;
extern lv_obj_t * ui_WiFiNoConnectBtnLab;
extern lv_obj_t * ui_WiFiNoConnectName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

